# Flusso di lavoro riproducibile con RMarkdown

## Motivazione 

> Per il metodo scientifico è essenziale che gli esperimenti siano riproducibili. Vale a dire che una persona diversa dallo sperimentatore originale deve essere in grado di ottenere gli stessi risultati seguendo lo stesso protocollo sperimentale. (Gilbert Chin)

Ma in psicologia (e non solo) la riproducibilità è inferiore a quanto previsto o desiderato. In un famoso studio pubblicato su “Science” un ampio gruppo di ricercatori [@open2015estimating] è riuscito a replicare solo il 40 per cento circa dei risultati di 100 studi di psicologia cognitiva e sociale pubblicati in precedenza. Questi risultati, ed molti altri risultati simili pubblicati in seguito, sono stati interpretati in modi diversi. La preoccupazione sulla riproducibilità della ricerca varia dall'affermare secondo la quale "la maggior parte dei risultati della ricerca sono falsi" [@ioannidis2005most] all'affermazione secondo cui "dobbiamo apportare modifiche sostanziali al modo in cui conduciamo la ricerca" [@cumming2014new]. Alcuni ricercatori sono arrivati a definire la situazione come una "crisi di riproducibilità" [@munafo2017manifesto].

Il termine "riproducibilità" (o "replicabilità") è definito in vari modi. Consideriamo qui la definizione fornita da @goodman2016does.

- La riproducibilità dei metodi "si riferisce al fatto che il ricercatore fornisce  dettagli sufficienti sulle procedure e sui dati dello studio in modo che le stesse procedure possano ... essere replicate esattamente" (pag. 2) con gli stessi dati.

- La riproducibilità dei risultati "si riferisce all'ottenimento degli stessi risultati dalla conduzione di uno studio indipendente le cui procedure replicano il più esattamente possibile quelle dell'esperimento originale" (pag. 2-3) con dati indipendenti.

- La riproducibilità inferenziale "si riferisce alla possibilità di trarre conclusioni qualitativamente simili da una replica indipendente di uno studio o da una nuova analisi dello studio originale" (pag. 4).

Per gli scopi di questo capitolo, ci focalizziamo qui sulla riproducibilità dei metodi. Cioè, discuteremo di come R può aiutarci a migliorare questo aspetto della riproducibilità. In questo capitolo mostreremo come R possa essere integrato in un flusso di lavoro riproducibile che è in grado di integrare i metodi di analisi dei dati, i dati medesimi e il report che comunica i risultati dello studio. Invece di limitarci a considerare il codice R, mostreremo come possiamo integrare codice, output e testo in un documento riproducibile. A tal fine utilizzeremo due pacchetti R: `rmarkdown` e `knitr`. Questi pacchetti ci consentono di unire un linguaggio di markup chiamato Markdown con il codice R.

## R Markdown

Markdown è un semplice linguaggio di linguaggio di markup in cui, mediante l'uso di alcuni simboli, è possibile cambiano l'aspetto tipografico del testo, ovvero realizzare la formattazione del testo. Un'introduzione a Markdown può essere trovata, per esempio, [qui](https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html). In questo capitolo ci limiteremo a discutere gli aspetti più importanti di R Markdown.

Per iniziare, consideriamo ciò che viene posto all'inizio di un documento `.Rmd` (R Markdown). Questa sezione del documento è chiamata YAML (un acronimo che significa Yet Another Markup Language). Lo YAML header controlla le caratteristiche generali del documento, incluso il tipo di documento che viene prodotto (un documento HTML che può essere visualizzato su tutti i principali browser, un documento Microsoft Word o un PDF se abbiamo installato $\LaTeX$ sul nostro computer), la dimensione del carattere, lo stile, il titolo, l'autore, ecc.

Nello YAML header (a differenza del codice R) è necessario rispettare la spaziatura prestabilita delle istruzioni che vengono elencate. Gli elementi principali sono questi:

```{r, eval=FALSE}
---
title: "Il titolo"
author: "Tu, l'autore"
output: html_document
---
```

L'argomento output è dove diciamo a R Markdown quale tipo di file vogliamo che venga prodotto. Il tipo più flessibile, che non richiede alcuna configurazione, è `html_document`.

Alla conclusione dello YAML header inizia il documento R Markdown. Da questo punto in poi possiamo utilizzare testo normale, codice R e sintassi Markdown per controllare cosa viene mostrato e come. È possibile contrassegnare intestazioni, grassetto e corsivo come indicato di seguito.

```
# Intestazione 1
## Intestazione 2
### Intestazione 3
#### Intestazione 4
##### Intestazione 5
###### Intestazione 6

Questo è un testo normale.
Possiamo scrivere in **grassetto** il testo usando due asterischi.
Possiamo scrivere in *corsivo* usando un asterisco.

>Questa è un’**area rientrata**.

Questa riga invece non è più rientrata.
```

Per creare un elenco casuale con markdown si utilizza il segno più, il trattino o l’asterisco. Tutte le tre soluzioni portano allo stesso risultato.

```
- Punto 1 della lista
- Punto 2 della lista
- Punto 3 della lista
```

Un elenco numerato, invece, si crea con un numero seguito da un punto.

```
1. Punto 1 della lista
2. Punto 2 della lista
3. Punto 3 della lista
```

Per contrassegnare un'area di testo come codice, markdown utilizza il cosiddetto backtick, noto anche come gravis o accento grave, da non confondere con la virgoletta singola. La marcatura prevede un accento all'inizio e uno alla fine dell'area di testo corrispondente.

```
Questo è `code`.
```

Oltre a contrassegnare un'area di testo come codice, possiamo anche includere il codice R vero e proprio direttamente nel testo così da valutare il codice all'interno del documento e da produrre un output che verrà stampato nel documento. Ciò significa che possiamo stampare tabelle e figure prodotti direttamente dal codice R. Inoltre, significa che se qualcosa cambia nelle analisi dei dati, le tabelle e le figure si aggiorneranno automaticamente.

Per includere un "chunk" di codice R, utilizziamo la seguente sintassi:

````markdown
`r ''````{r}
## il codice R va qui
```
````

Un chunk R verrà valutato proprio come il normale codice R, quindi si applica tutto ciò che abbiamo imparato nei capitoli precedenti. Se il chunk R produce un output, questo output verrà visualizzato nel documento.

Ma dove si trova questo magico documento include il testo che abbiamo scritto e l'output dei chunk di R? Ottima domanda. Questo è qualcosa a cui la maggior parte di noi non è abituata. Coloro che hanno utilizzato altri programmi di videoscrittura (come Microsoft Word) sono abitutai al cosiddetto stile "WYSIWYG" (What You See Is What You Get). Cioè, si vede come apparirà il documento stampato mentre lo si digita. Questo può avere alcuni vantaggi ma può anche essere molto limitante.

R Markdown, d'altra parte, deve essere "compilato" (knit) per produrre il documento formattato. In RStudio, tale operazione è semplice. C'è un pulsante in alto a sinistra nel pannello di scripting di un documento `.Rmd`. Selezionando questo pulsante, il nostro documento verrà creato.

## Importante

Il codice del documento deve essere completamente autonomo. Ciò significa che tutto ciò che volete che venga eseguito deve essere nel documento, indipendentemente da ciò che è stato già eseguito al di fuori di esso. Ad esempio, è perfettamente legittimo (e anche molto utile) testare il codice R al di fuori del documento `Rmd`. Tuttavia, quando compiliamo il documento `Rmd`, tutto ciò che è stato fatto al di fuori del documento `Rmd` viene dimenticato. Ciò consente di creare un documento autosufficiente che favorisce la riproducibilità dei metodi di analisi dei dati: utilizzando uno specifico documento `Rmd` con un campione di dati si giunge sempre allo stesso risultato e alla stessa interpretazione. Ciò non è invece vero se si utilizza un software con un interfaccia point-and-click.


