<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capitolo 4 Statistica descrittiva | PSICOMETRIA</title>
  <meta name="description" content="Queste dispense si propongono di fornire un’introduzione all’analisi dei dati psicologici agli studenti del primo anno del Corso di Laurea in Scienze e Tecniche Psicologiche. Particolare attenzione sarà posta ai seguenti aspetti: l’uso del linguaggio R per lo svolgimento delle analisi statistiche, la rappresentazione grafica dei dati e l’inferenza Bayesiana." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Capitolo 4 Statistica descrittiva | PSICOMETRIA" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Queste dispense si propongono di fornire un’introduzione all’analisi dei dati psicologici agli studenti del primo anno del Corso di Laurea in Scienze e Tecniche Psicologiche. Particolare attenzione sarà posta ai seguenti aspetti: l’uso del linguaggio R per lo svolgimento delle analisi statistiche, la rappresentazione grafica dei dati e l’inferenza Bayesiana." />
  <meta name="github-repo" content="ccaudek/bookdown_psicometria" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capitolo 4 Statistica descrittiva | PSICOMETRIA" />
  <meta name="twitter:site" content="@ccaudek" />
  <meta name="twitter:description" content="Queste dispense si propongono di fornire un’introduzione all’analisi dei dati psicologici agli studenti del primo anno del Corso di Laurea in Scienze e Tecniche Psicologiche. Particolare attenzione sarà posta ai seguenti aspetti: l’uso del linguaggio R per lo svolgimento delle analisi statistiche, la rappresentazione grafica dei dati e l’inferenza Bayesiana." />
  

<meta name="author" content="Corrado Caudek" />


<meta name="date" content="2020-12-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chapter-misurazione.html"/>
<link rel="next" href="chapter-prob-discreta.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A.A. 2020/2021</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefazione</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#perché-tanta-statistica-in-psicologia"><i class="fa fa-check"></i>Perché tanta statistica in psicologia?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#come-studiare"><i class="fa fa-check"></i>Come studiare?</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="chapter-pacchetti.html"><a href="chapter-pacchetti.html"><i class="fa fa-check"></i><b>1</b> Pacchetti</a></li>
<li class="chapter" data-level="2" data-path="chapter-terminologia.html"><a href="chapter-terminologia.html"><i class="fa fa-check"></i><b>2</b> Terminologia</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chapter-terminologia.html"><a href="chapter-terminologia.html#metodi-e-procedure-della-psicologia"><i class="fa fa-check"></i><b>2.1</b> Metodi e procedure della psicologia</a></li>
<li class="chapter" data-level="2.2" data-path="chapter-terminologia.html"><a href="chapter-terminologia.html#variabili-e-costanti"><i class="fa fa-check"></i><b>2.2</b> Variabili e costanti</a></li>
<li class="chapter" data-level="2.3" data-path="chapter-terminologia.html"><a href="chapter-terminologia.html#variabili-indipendenti-e-variabili-dipendenti"><i class="fa fa-check"></i><b>2.3</b> Variabili indipendenti e variabili dipendenti</a></li>
<li class="chapter" data-level="2.4" data-path="chapter-terminologia.html"><a href="chapter-terminologia.html#la-matrice-dei-dati"><i class="fa fa-check"></i><b>2.4</b> La matrice dei dati</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html"><i class="fa fa-check"></i><b>3</b> La misurazione in psicologia</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#le-scale-di-misura"><i class="fa fa-check"></i><b>3.1</b> Le scale di misura</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#scala-nominale"><i class="fa fa-check"></i><b>3.1.1</b> Scala nominale</a></li>
<li class="chapter" data-level="3.1.2" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#scala-ordinale"><i class="fa fa-check"></i><b>3.1.2</b> Scala ordinale</a></li>
<li class="chapter" data-level="3.1.3" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#scala-ad-intervalli"><i class="fa fa-check"></i><b>3.1.3</b> Scala ad intervalli</a></li>
<li class="chapter" data-level="3.1.4" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#scala-di-rapporti"><i class="fa fa-check"></i><b>3.1.4</b> Scala di rapporti</a></li>
<li class="chapter" data-level="3.1.5" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#gerarchia-dei-livelli-di-scala-di-misura"><i class="fa fa-check"></i><b>3.1.5</b> Gerarchia dei livelli di scala di misura</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#sec:DiscreteVsContinuous"><i class="fa fa-check"></i><b>3.2</b> Variabili discrete vs. variabili continue</a></li>
<li class="chapter" data-level="3.3" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#perché-alcune-misurazioni-sono-migliori-di-altre"><i class="fa fa-check"></i><b>3.3</b> Perché alcune misurazioni sono migliori di altre?</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#sec:accuratezza_precisione"><i class="fa fa-check"></i><b>3.3.1</b> Tipologie di errori</a></li>
<li class="chapter" data-level="3.3.2" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#sec:reliability"><i class="fa fa-check"></i><b>3.3.2</b> Attendibilità</a></li>
<li class="chapter" data-level="3.3.3" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#sec:validity"><i class="fa fa-check"></i><b>3.3.3</b> Validità</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#conclusioni"><i class="fa fa-check"></i>Conclusioni</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html"><i class="fa fa-check"></i><b>4</b> Statistica descrittiva</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#perché-riassumere-i-dati"><i class="fa fa-check"></i><b>4.1</b> Perché riassumere i dati?</a></li>
<li class="chapter" data-level="4.2" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#sec:distr_freq"><i class="fa fa-check"></i><b>4.2</b> Distribuzioni di frequenze</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#esercizio-con-r"><i class="fa fa-check"></i><b>4.2.1</b> Esercizio con R</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#istogramma"><i class="fa fa-check"></i><b>4.3</b> Istogramma</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#esercizio-con-r-1"><i class="fa fa-check"></i><b>4.3.1</b> Esercizio con R</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#funzione-di-densità-empirica"><i class="fa fa-check"></i><b>4.4</b> Funzione di densità empirica</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#esercizio-con-r-2"><i class="fa fa-check"></i><b>4.4.1</b> Esercizio con R</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#forma-di-una-distribuzione"><i class="fa fa-check"></i><b>4.5</b> Forma di una distribuzione</a></li>
<li class="chapter" data-level="4.6" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#indici-di-posizione"><i class="fa fa-check"></i><b>4.6</b> Indici di posizione</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#quantili"><i class="fa fa-check"></i><b>4.6.1</b> Quantili</a></li>
<li class="chapter" data-level="4.6.2" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#box-plot"><i class="fa fa-check"></i><b>4.6.2</b> Box-plot</a></li>
<li class="chapter" data-level="4.6.3" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#leccellenza-grafica"><i class="fa fa-check"></i><b>4.6.3</b> L’eccellenza grafica</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#indici-di-tendenza-centrale"><i class="fa fa-check"></i><b>4.7</b> Indici di tendenza centrale</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#media"><i class="fa fa-check"></i><b>4.7.1</b> Media</a></li>
<li class="chapter" data-level="4.7.2" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#media-spuntata"><i class="fa fa-check"></i><b>4.7.2</b> Media spuntata</a></li>
<li class="chapter" data-level="4.7.3" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#moda-e-mediana"><i class="fa fa-check"></i><b>4.7.3</b> Moda e mediana</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#indici-di-dispersione"><i class="fa fa-check"></i><b>4.8</b> Indici di dispersione</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#indici-basati-sullordinamento-dei-dati"><i class="fa fa-check"></i><b>4.8.1</b> Indici basati sull’ordinamento dei dati</a></li>
<li class="chapter" data-level="4.8.2" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#scostamento-medio-semplice-dalla-media"><i class="fa fa-check"></i><b>4.8.2</b> Scostamento medio semplice dalla media</a></li>
<li class="chapter" data-level="4.8.3" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#varianza"><i class="fa fa-check"></i><b>4.8.3</b> Varianza</a></li>
<li class="chapter" data-level="4.8.4" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#deviazione-standard"><i class="fa fa-check"></i><b>4.8.4</b> Deviazione standard</a></li>
<li class="chapter" data-level="4.8.5" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#indici-di-variabilità-relativi"><i class="fa fa-check"></i><b>4.8.5</b> Indici di variabilità relativi</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#le-relazioni-tra-variabili"><i class="fa fa-check"></i><b>4.9</b> Le relazioni tra variabili</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#diagramma-a-dispersione"><i class="fa fa-check"></i><b>4.9.1</b> Diagramma a dispersione</a></li>
<li class="chapter" data-level="4.9.2" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#covarianza"><i class="fa fa-check"></i><b>4.9.2</b> Covarianza</a></li>
<li class="chapter" data-level="4.9.3" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#correlazione"><i class="fa fa-check"></i><b>4.9.3</b> Correlazione</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#correlazione-e-causazione"><i class="fa fa-check"></i><b>4.10</b> Correlazione e causazione</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#usi-della-correlazione"><i class="fa fa-check"></i><b>4.10.1</b> Usi della correlazione</a></li>
<li class="chapter" data-level="4.10.2" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#correlazione-di-spearman"><i class="fa fa-check"></i><b>4.10.2</b> Correlazione di Spearman</a></li>
<li class="chapter" data-level="4.10.3" data-path="chapter-descriptive-stats.html"><a href="chapter-descriptive-stats.html#correlazione-nulla"><i class="fa fa-check"></i><b>4.10.3</b> Correlazione nulla</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#conclusioni"><i class="fa fa-check"></i>Conclusioni</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html"><i class="fa fa-check"></i><b>5</b> Che cos’è la probabilità?</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#probabilità-nel-linguaggio-naturale"><i class="fa fa-check"></i><b>5.1</b> Probabilità nel linguaggio naturale</a></li>
<li class="chapter" data-level="5.2" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#probabilità-nel-linguaggio-scientifico"><i class="fa fa-check"></i><b>5.2</b> Probabilità nel linguaggio scientifico</a></li>
<li class="chapter" data-level="5.3" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#terminologia"><i class="fa fa-check"></i><b>5.3</b> Terminologia</a></li>
<li class="chapter" data-level="5.4" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#le-diverse-definizioni-della-probabilità"><i class="fa fa-check"></i><b>5.4</b> Le diverse definizioni della probabilità</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#sec:def_ing_prob"><i class="fa fa-check"></i><b>5.4.1</b> Una definizione “ingenua” della probabilità</a></li>
<li class="chapter" data-level="5.4.2" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#una-definizione-non-ingenua-della-probabilità"><i class="fa fa-check"></i><b>5.4.2</b> Una definizione “non ingenua” della probabilità</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#assegnare-le-probabilità-agli-eventi"><i class="fa fa-check"></i><b>5.5</b> Assegnare le probabilità agli eventi</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#approccio-frequentista"><i class="fa fa-check"></i><b>5.5.1</b> Approccio frequentista</a></li>
<li class="chapter" data-level="5.5.2" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#approccio-bayesiano"><i class="fa fa-check"></i><b>5.5.2</b> Approccio Bayesiano</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#proprietà-elementari-della-probabilità"><i class="fa fa-check"></i><b>5.6</b> Proprietà elementari della probabilità</a></li>
<li class="chapter" data-level="5.7" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#variabili-aleatorie"><i class="fa fa-check"></i><b>5.7</b> Variabili aleatorie</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#a-cosa-servono-le-variabili-aleatorie"><i class="fa fa-check"></i><b>5.7.1</b> A cosa servono le variabili aleatorie?</a></li>
<li class="chapter" data-level="5.7.2" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#funzione-di-massa-di-probabilità"><i class="fa fa-check"></i><b>5.7.2</b> Funzione di massa di probabilità</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="chapter-prob-discreta.html"><a href="chapter-prob-discreta.html#notazione"><i class="fa fa-check"></i><b>5.8</b> Notazione</a></li>
<li class="chapter" data-level="" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#conclusioni"><i class="fa fa-check"></i>Conclusioni</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chapter-prob-cond.html"><a href="chapter-prob-cond.html"><i class="fa fa-check"></i><b>6</b> Probabilità condizionata</a>
<ul>
<li class="chapter" data-level="6.1" data-path="chapter-prob-cond.html"><a href="chapter-prob-cond.html#sec:prob_cond"><i class="fa fa-check"></i><b>6.1</b> Probabilità condizionata su altri eventi</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="chapter-prob-cond.html"><a href="chapter-prob-cond.html#la-fallacia-del-pubblico-ministero"><i class="fa fa-check"></i><b>6.1.1</b> La fallacia del pubblico ministero</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="chapter-prob-cond.html"><a href="chapter-prob-cond.html#legge-della-probabilità-composta"><i class="fa fa-check"></i><b>6.2</b> Legge della probabilità composta</a></li>
<li class="chapter" data-level="6.3" data-path="chapter-prob-cond.html"><a href="chapter-prob-cond.html#lindipendendenza-stocastica"><i class="fa fa-check"></i><b>6.3</b> L’indipendendenza stocastica</a></li>
<li class="chapter" data-level="" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#conclusioni"><i class="fa fa-check"></i>Conclusioni</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chapter-bayes-theo.html"><a href="chapter-bayes-theo.html"><i class="fa fa-check"></i><b>7</b> Il teorema di Bayes</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chapter-bayes-theo.html"><a href="chapter-bayes-theo.html#sec:tot_prob_theorem"><i class="fa fa-check"></i><b>7.1</b> Il teorema della probabilità totale</a></li>
<li class="chapter" data-level="7.2" data-path="chapter-bayes-theo.html"><a href="chapter-bayes-theo.html#sec:bayes_theorem"><i class="fa fa-check"></i><b>7.2</b> Il teorema della probabilità delle cause</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="chapter-bayes-theo.html"><a href="chapter-bayes-theo.html#aggiornamento-bayesiano"><i class="fa fa-check"></i><b>7.2.1</b> Aggiornamento Bayesiano</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#conclusioni"><i class="fa fa-check"></i>Conclusioni</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chapter-distr-congiunta.html"><a href="chapter-distr-congiunta.html"><i class="fa fa-check"></i><b>8</b> Probabilità congiunta</a>
<ul>
<li class="chapter" data-level="8.1" data-path="chapter-distr-congiunta.html"><a href="chapter-distr-congiunta.html#funzione-di-probabilità-congiunta"><i class="fa fa-check"></i><b>8.1</b> Funzione di probabilità congiunta</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="chapter-distr-congiunta.html"><a href="chapter-distr-congiunta.html#proprietà"><i class="fa fa-check"></i><b>8.1.1</b> Proprietà</a></li>
<li class="chapter" data-level="8.1.2" data-path="chapter-distr-congiunta.html"><a href="chapter-distr-congiunta.html#eventi"><i class="fa fa-check"></i><b>8.1.2</b> Eventi</a></li>
<li class="chapter" data-level="8.1.3" data-path="chapter-distr-congiunta.html"><a href="chapter-distr-congiunta.html#funzioni-di-probabilità-marginali"><i class="fa fa-check"></i><b>8.1.3</b> Funzioni di probabilità marginali</a></li>
<li class="chapter" data-level="8.1.4" data-path="chapter-distr-congiunta.html"><a href="chapter-distr-congiunta.html#indipendenza-stocastica"><i class="fa fa-check"></i><b>8.1.4</b> Indipendenza stocastica</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-misurazione.html"><a href="chapter-misurazione.html#conclusioni"><i class="fa fa-check"></i>Conclusioni</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html"><i class="fa fa-check"></i>Appendici</a>
<ul>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#simbologia-di-base"><i class="fa fa-check"></i>Simbologia di base</a></li>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#numeri-binari-interi-razionali-irrazionali-e-reali"><i class="fa fa-check"></i>Numeri binari, interi, razionali, irrazionali e reali</a>
<ul>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#numeri-binari"><i class="fa fa-check"></i>Numeri binari</a></li>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#numeri-interi"><i class="fa fa-check"></i>Numeri interi</a></li>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#numeri-razionali"><i class="fa fa-check"></i>Numeri razionali</a></li>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#numeri-irrazionali"><i class="fa fa-check"></i>Numeri irrazionali</a></li>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#numeri-reali"><i class="fa fa-check"></i>Numeri reali</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#intervalli"><i class="fa fa-check"></i>Intervalli</a></li>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#cap:insiemi"><i class="fa fa-check"></i>Insiemi</a>
<ul>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#operazioni-tra-insiemi"><i class="fa fa-check"></i>Operazioni tra insiemi</a></li>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#diagrammi-di-eulero-venn"><i class="fa fa-check"></i>Diagrammi di Eulero-Venn</a></li>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#sec:prod_cartesiano"><i class="fa fa-check"></i>Coppie ordinate e prodotto cartesiano</a></li>
<li class="chapter" data-level="" data-path="appendici.html"><a href="appendici.html#cardinalità"><i class="fa fa-check"></i>Cardinalità</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliografia.html"><a href="bibliografia.html"><i class="fa fa-check"></i>Bibliografia</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PSICOMETRIA</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter:descriptive-stats" class="section level1" number="4">
<h1><span class="header-section-number">Capitolo 4</span> Statistica descrittiva</h1>
<p>Nel 1907 Francis Galton, cugino di Charles Darwin, matematico e
statistico autodidatta, geografo, esploratore, teorico della
dattiloscopia (ovvero, dell’uso delle impronte digitali a fini
identificativi) e dell’eugenetica, scrisse una lettera alla rivista
scientifica Nature sulla sua visita alla <em>Fat Stock and Poultry
Exhibition</em> di Plymouth. Lì vide alcuni membri del pubblico partecipare
ad un gioco il cui scopo era quello di indovinare il peso della carcassa
di un grande bue che era appena stato scuoiato. Galton si procurò i 787
dei biglietti che erano stati compilati dal pubblico e considerò il
valore medio di 547 kg come la “scelta democratica” dei partecipanti, in
quanto “ogni altra stima era stata giudicata troppo alta o troppo bassa
dalla maggioranza dei votanti.” Il punto interessante è che il peso
corretto di 543 kg si dimostrò essere molto simile alla “scelta
democratica” basata sulle stime dei 787 partecipanti. Galton intitolò la
sua lettera a Nature <em>Vox Populi</em> (voce del popolo), ma questo processo
decisionale è ora meglio conosciuto come la “saggezza delle folle”
(<em>wisdom of crowds</em>). Possiamo dire che, nel suo articolo del 1907,
Galton effettuò quello che ora chiamiamo un riepilogo dei dati, ovvero
calcolò un indice sintetico a partire da un insieme di dati. In questo
capitolo esamineremo le tecniche che sono state sviluppate nel secolo
successivo per riassumere le grandi masse di dati con cui sempre più
spesso ci dobbiamo confrontare. Vedremo come calcolare e interpretare
gli indici di posizione e di dispersione, discuteremo le distribuzioni
di frequenze e le relazioni tra variabili. Vedremo inoltre quali sono le
tecniche di visualizzazione che ci consentono di rappresentare questi
sommari dei dati mediante dei grafici. Ma prima di entrare nei dettagli,
prendiamoci un momento per capire perché abbiamo bisogno della
statistica descrittiva.</p>
<div id="perché-riassumere-i-dati" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Perché riassumere i dati?</h2>
<p>Quando riassumiamo i dati, necessariamente buttiamo via delle
informazioni. Ma è una buona idea procedere in questo modo? Non sarebbe
meglio conservare le informazioni specifiche di ciascun soggetto che
partecipa ad un esperimento psicologico, al di là di ciò che viene
trasmesso dagli indici riassuntivi della statistica descrittiva? Che
dire delle informazioni che descrivono come sono stati raccolti i dati,
come l’ora del giorno o l’umore del partecipante? Tutte queste
informazioni vengono perdute quando riassumiamo i dati. La risposta alla
domanda che ci siamo posti è che, in generale, non è una buona idea
conservare tutti i dettagli di ciò che sappiamo. È molto più utile
riassumere le informazioni perché la semplificazione risultante consente
i processi di <strong>generalizzazione</strong>.</p>
<p>In un contesto letterario, l’importanza della generalizzazione è stata
sottolineata da Jorge Luis Borges nel suo racconto “Funes o della
memoria,” che descrive un individuo che perde la capacità di
dimenticare. Borges si concentra sulla relazione tra generalizzazione e
pensiero:</p>
<blockquote>
<p>Pensare è dimenticare una differenza, generalizzare, astrarre. Nel mondo troppo pieno di Funes, c’erano solo dettagli.</p>
</blockquote>
<p>Come possiamo ben capire, la vita di Funes non è facile. Se facciamo
riferimento alla psicologia possiamo dire che gli psicologi hanno
studiato a lungo l’utilità della generalizzazione per il pensiero. Un
esempio è fornito dal fenomeno della formazione dei concetti e lo
psicologo che viene in mente a questo proposito è sicuramente Eleanor
Rosch, la quale ha studiato i principi di base della categorizzazione. I
concetti ci forniscono uno strumento potente per organizzare le
conoscenze. Noi siamo in grado di riconoscere facilmente i diversi
esemplare di un concetto – per esempio, “gli uccelli” – anche se i
singoli esemplari che fanno parte di una categoria sono molto diversi
tra loro (l’aquila, la gallina, il pettirosso). L’uso dei concetti, cioè
la generalizzazione, è utile perché ci consente di fare previsioni sulle
proprietà dei singoli esemplari che appartengono ad una categoria, anche
se non abbiamo mai avuto esperienza diretta con essi – per esempio,
possiamo fare la predizione che tutti gli uccelli possono volare e
mangiare vermi, ma non possono guidare un’automobile o parlare in
inglese. Queste previsioni non sono sempre corrette, ma sono utili.</p>
<p>Le statistiche descrittive, in un certo senso, ci fornisco l’analogo dei
“prototipi” che, secondo Eleanor Rosch, stanno alla base del processo
psicologico di creazione dei concetti. Un prototipo è l’esemplare più
rappresentativo di una categoria. In maniera simile, una statistica
descrittiva come la media, ad esempio, potrebbe essere intesa come
l’osservazione “tipica.”</p>
<p>La statistica descrittiva ci fornisce gli strumenti per riassumere i
dati che abbiamo a disposizione in una forma visiva o numerica. Le
rappresentazioni grafiche più usate della statistica descrittiva sono
gli istogrammi, i diagrammi a dispersione o i box-plot, e gli indici
sintetici più comuni sono la media, la mediana, la varianza e la
deviazione standard.</p>
</div>
<div id="sec:distr_freq" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Distribuzioni di frequenze</h2>
<p>Per introdurre i principali strumenti della statistica descrittiva
considereremo qui i dati raccolti da <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>. Questi autori
hanno studiato le aspettative negative le quali sono state evidenziate
come un meccanismo chiave nel mantenimento e nella reiterazione della
depressione. <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span> hanno valutato le aspettative di
individui depressi circa il loro umore futuro ed si sono chiesti se
queste aspettative fossero accurate oppure distorte negativamente.</p>
<p>In uno degli studi descritti viene esaminato un campione costituito da 30
soggetti con almeno un episodio depressivo maggiore e da 37 controlli
sani. Gli autori hanno misurato il livello depressivo con il <em>Beck
Depression Inventory</em> (BDI-II). Ma qual è la la gravità della
depressione riportata dai soggetti nel campione esaminato da
<span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>?</p>
<p>Dei 67 soggetti considerati, uno non ha completato il BDI-II e quindi abbiamo a disposizione 66 valori del BDI-II.
I dati sono riportati nella tabella [tab:bdi2_values].
Per semplicità i dati sono stati ordinati in
ordine crescente. È chiaro che i dati grezzi sono di difficile lettura.
Poniamoci dunque il problema di creare una rappresentazione sintetica e
comprensibile di questo insieme di valori.</p>
<p>Uno dei modi che ci consentono di effettuare una sintesi dei dati è
quello di generare una <em>distribuzione di frequenze</em>.
Una distribuzione di frequenze è un riepilogo del conteggio della
frequenza con cui le modalità osservate in un insieme di dati si
verificano in un intervallo di valori.</p>
<p>Per creare una distribuzione di frequenze possiamo procedere effettuando
una partizione delle modalità della variabile di interesse in <span class="math inline">\(m\)</span> classi
(denotate con <span class="math inline">\(\Delta_i\)</span>) tra loro disgiunte. In tale partizione, la
classe <span class="math inline">\(i\)</span>-esima coincide con un intervallo di valori aperto a destra
<span class="math inline">\([a_i, b_i)\)</span> o aperto a sinistra <span class="math inline">\((a_i, b_i]\)</span>. Ad ogni classe
<span class="math inline">\(\Delta_i\)</span> avente <span class="math inline">\(a_i\)</span> e <span class="math inline">\(b_i\)</span> come limite inferiore e superiore
associamo l’ampiezza <span class="math inline">\(b_i - a_i\)</span> (non necessariamente uguale per ogni
classe) e il valore centrale <span class="math inline">\(\bar{x}_i\)</span>. La scelta delle classi è
arbitraria, ma è buona norma non definire classi con un numero troppo
piccolo (&lt; 5) di osservazioni. Poiché ogni elemento dell’insieme
<span class="math inline">\(\{x_i\}_{i=1}^n\)</span> appartiene ad una ed una sola classe <span class="math inline">\(\Delta_i\)</span>,
possiamo calcolare le quantità elencate di seguito.</p>
<ul>
<li><p>La <strong>frequenza assoluta</strong> <span class="math inline">\(n_i\)</span> di ciascuna classe, ovvero il numero di osservazioni che ricadono nella classe <span class="math inline">\(\Delta_i\)</span>.
Proprietà: <span class="math inline">\(n_1 + n_2 + \dots + n_m = n\)</span>.</p></li>
<li><p>La <strong>frequenza relativa</strong> <span class="math inline">\(f_i = n_i/n\)</span> di ciascuna classe. Proprietà: <span class="math inline">\(f_1+f_2+\dots+f_m =1\)</span>.</p></li>
<li><p>La <strong>frequenza cumulata</strong> <span class="math inline">\(N_i\)</span>, ovvero il numero totale delle osservazioni che ricadono nelle classi fino alla <span class="math inline">\(i\)</span>-esima compresa: <span class="math inline">\(N_i = \sum_{i=1}^m n_i.\)</span></p></li>
<li><p>La <strong>frequenza cumulata relativa</strong> <span class="math inline">\(F_i\)</span>, ovvero
<span class="math inline">\(F_i = f_1+f_2+\dots+f_m = \frac{N_i}{n} = \frac{1}{n} \sum_{i=1}^m f_i.\)</span></p></li>
</ul>
<p>Calcoliamo ora la distribuzione di frequenza assoluta e la distribuzione di frequenza relativa per i valori del BDI-II del campione clinico di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>.
Per costruire una distribuzione di frequenza è innanzitutto necessario scegliere gli
intervalli delle classi. Facendo riferimento ai cut-off usati per l’interpretazione del BDI-II, definiamo i seguenti <strong>intervalli aperti a destra</strong>:</p>
<ul>
<li>depressione minima: [0, 13.5),</li>
<li>depressione lieve: [13.5, 19.5),</li>
<li>depressione moderata: [19.5, 28.5),</li>
<li>depressione severa: [28.5, 63).</li>
</ul>
<p>La distribuzione di frequenza della variabile <code>bdi2</code> è riportata nella
tabella seguente. Questa distribuzione di frequenza ci aiuta a capire meglio cosa sta succedendo. Se consideriamo la frequenza relativa, ad esempio, possiamo notare che ci sono due valori maggiormente ricorrenti e tali valori corrispondono alle due classi più estreme. Questo ha senso nel caso presente, in quanto il campione esaminato da <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span> includeva due gruppi di
soggetti: soggetti sani (con valori BDI-II bassi) e soggetti depressi
(con valori BDI-II alti). In una distribuzione di frequenza tali valori
tipici vanno sotto il nome di <strong>mode</strong> della distribuzione.</p>
<table>
<thead>
<tr class="header">
<th align="center">Limiti delle classi</th>
<th align="center">Freq. ass.</th>
<th align="center">Freq. rel.</th>
<th align="center">Freq. ass. cum.</th>
<th align="center">Freq. rel. cum.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\([0, 13.5)\)</span></td>
<td align="center">36</td>
<td align="center">36/66</td>
<td align="center">36</td>
<td align="center">36/66</td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\([13.5, 19.5)\)</span></td>
<td align="center">1</td>
<td align="center">1/66</td>
<td align="center">37</td>
<td align="center">37/66</td>
</tr>
<tr class="odd">
<td align="center"><span class="math inline">\([19.5, 28.5)\)</span></td>
<td align="center">12</td>
<td align="center">12/66</td>
<td align="center">49</td>
<td align="center">49/66</td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\([28.5, 63)\)</span></td>
<td align="center">17</td>
<td align="center">17/66</td>
<td align="center">66</td>
<td align="center">66/66</td>
</tr>
</tbody>
</table>
<div id="esercizio-con-r" class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Esercizio con R</h3>
<p>Poniamoci ora il problema di costruire la tabella precedente partendo dai dati grezzi messi a disposizione da <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>.
Leggiamo i dati assumendo che il file <code>data.mood.csv</code> si trovi nella cartella <code>data</code> contenuta nella <em>working directory</em>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="chapter-descriptive-stats.html#cb4-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(</span>
<span id="cb4-2"><a href="chapter-descriptive-stats.html#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;data.mood.csv&quot;</span>), </span>
<span id="cb4-3"><a href="chapter-descriptive-stats.html#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">header=</span><span class="cn">TRUE</span></span>
<span id="cb4-4"><a href="chapter-descriptive-stats.html#cb4-4" aria-hidden="true" tabindex="-1"></a>) </span></code></pre></div>
<p>C’è un solo valore di depressione per ciascun soggetto ma tale valore viene ripetuto tante volte quante volte sono le righe del <code>data.frame</code> associate ad ogni soggetto (ciascuna riga corrispondente ad una prova diversa). È dunque necessario trasformare il <code>data.frame</code> in modo tale da avere un’unica riga per ciascun soggetto, ovvero un unico valore BDI-II per soggetto.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="chapter-descriptive-stats.html#cb5-1" aria-hidden="true" tabindex="-1"></a>bysubj <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="chapter-descriptive-stats.html#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(esm_id) <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="chapter-descriptive-stats.html#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-4"><a href="chapter-descriptive-stats.html#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">bdi =</span> <span class="fu">mean</span>(bdi)</span>
<span id="cb5-5"><a href="chapter-descriptive-stats.html#cb5-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb5-6"><a href="chapter-descriptive-stats.html#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<p>Ci sono dunque 66 soggetti i quali hanno ottenuto i valori sulla scala del BDI-II stampati di seguito (li presento ordinati dal più piccolo al più grande).</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="chapter-descriptive-stats.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(bysubj<span class="sc">$</span>bdi)</span></code></pre></div>
<pre><code>##  [1]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  2
## [27]  2  2  2  3  3  3  5  7  9 12 19 22 22 24 25 25 26 26 26 27 27 28 28 30 30 30
## [53] 31 31 33 33 34 35 35 35 36 39 41 43 43 44</code></pre>
<p>Calcolo ora le frequenze assolute per i seguenti intervalli aperti a destra: [0, 13.5), [13.5, 19.5), [19.5, 28.5), [28.5, 63). Esaminando i dati, possiamo notare che 36 soggetti cadono nella prima classe. È però necessario eseguire quest’operazione di conteggio utilizzando R.</p>
<p>Uno dei modi possibili per calcolare le frequenze assolute è quello di usare la funzione <code>cut()</code>. Mediante tal funzione è possibile dividere il <em>campo di variazione</em> (ovvero, la differenza tra il valore massimo di una distribuzione ed il valore minimo) di una variabile continua <code>x</code> in intervalli e codificare ciascun valore <code>x</code> nei termini dell’intervallo a cui appartiene. Tale risultato si ottiene nel modo seguente.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="chapter-descriptive-stats.html#cb9-1" aria-hidden="true" tabindex="-1"></a>bysubj<span class="sc">$</span>bdi_level <span class="ot">&lt;-</span> <span class="fu">cut</span>(</span>
<span id="cb9-2"><a href="chapter-descriptive-stats.html#cb9-2" aria-hidden="true" tabindex="-1"></a>  bysubj<span class="sc">$</span>bdi,</span>
<span id="cb9-3"><a href="chapter-descriptive-stats.html#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">13.5</span>, <span class="fl">19.5</span>, <span class="fl">28.5</span>, <span class="dv">63</span>),</span>
<span id="cb9-4"><a href="chapter-descriptive-stats.html#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">include.lowest =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-5"><a href="chapter-descriptive-stats.html#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb9-6"><a href="chapter-descriptive-stats.html#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;minimal&quot;</span>, <span class="st">&quot;mild&quot;</span>, <span class="st">&quot;moderate&quot;</span>, <span class="st">&quot;severe&quot;</span></span>
<span id="cb9-7"><a href="chapter-descriptive-stats.html#cb9-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-8"><a href="chapter-descriptive-stats.html#cb9-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-9"><a href="chapter-descriptive-stats.html#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="chapter-descriptive-stats.html#cb9-10" aria-hidden="true" tabindex="-1"></a>bysubj<span class="sc">$</span>bdi_level</span></code></pre></div>
<pre><code>##  [1] moderate severe   severe   moderate severe   severe   severe   severe  
##  [9] moderate severe   moderate mild     severe   minimal  minimal  minimal 
## [17] severe   moderate minimal  minimal  minimal  minimal  minimal  moderate
## [25] minimal  minimal  minimal  minimal  minimal  minimal  minimal  severe  
## [33] minimal  minimal  severe   minimal  moderate minimal  minimal  minimal 
## [41] severe   minimal  minimal  severe   severe   moderate severe   severe  
## [49] minimal  moderate minimal  moderate severe   moderate moderate minimal 
## [57] minimal  minimal  minimal  minimal  minimal  minimal  minimal  minimal 
## [65] minimal  minimal 
## Levels: minimal mild moderate severe</code></pre>
<p>Possiamo ora usare la funzione <code>table()</code> la quale ritorna un elenco che associa la frequenza assoluta a ciascuna modalità della variabile in input – ovvero, la distribuzione di frequenza assoluta.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="chapter-descriptive-stats.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(bysubj<span class="sc">$</span>bdi_level)</span></code></pre></div>
<pre><code>## 
##  minimal     mild moderate   severe 
##       36        1       12       17</code></pre>
<p>Per ottenere la distribuzione di frequenza relativa è sufficiente dividere ciascuna frequenza assoluta per il numero totale di osservazioni:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="chapter-descriptive-stats.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(bysubj<span class="sc">$</span>bdi_level) <span class="sc">/</span> <span class="fu">sum</span>(<span class="fu">table</span>(bysubj<span class="sc">$</span>bdi_level))</span></code></pre></div>
<pre><code>## 
##    minimal       mild   moderate     severe 
## 0.54545455 0.01515152 0.18181818 0.25757576</code></pre>
<p>In questo modo abbiamo ottenuto le distribuzioni di frequenza assoluta e relativa per i valori del BDI-II dei soggetti di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>:</p>
<table>
<thead>
<tr class="header">
<th>Limiti delle classi</th>
<th>Frequenza assoluta</th>
<th>Frequenza relativa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>[0, 13.5)</td>
<td>36</td>
<td>36/66</td>
</tr>
<tr class="even">
<td>[13.5, 19.5)</td>
<td>1</td>
<td>1/66</td>
</tr>
<tr class="odd">
<td>[19.5, 28.5)</td>
<td>12</td>
<td>12/66</td>
</tr>
<tr class="even">
<td>[28.5, 63]</td>
<td>17</td>
<td>17/66</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="istogramma" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Istogramma</h2>
<p>I dati che sono stati sintetizzati in una distribuzione di frequenze
possono essere rappresentati graficamente in un istogramma.
Un istogramma si costruisce riportando sulle ascisse i limiti delle
classi <span class="math inline">\(\Delta_i\)</span> e sulle ordinate i valori della funzione costante a
tratti
<span class="math display">\[\varphi_n(x)= \frac{f_i}{b_i-a_i}, \quad x\in \Delta_i,\, i=1, \dots, m\]</span>
che misura la <strong>densità della frequenza relativa</strong> della variabile <span class="math inline">\(X\)</span>
nella classe <span class="math inline">\(\Delta_i\)</span>, ovvero il rapporto fra la frequenza relativa
<span class="math inline">\(f_i\)</span> e l’ampiezza (<span class="math inline">\(b_i - a_i\)</span>) della classe. In questo modo il
rettangolo dell’istogramma associato alla classe <span class="math inline">\(\Delta_i\)</span> avrà un’area
proporzionale alla frequenza relativa <span class="math inline">\(f_i\)</span>. Si noti che l’area totale
dell’istogramma delle frequenze relative è data della somma delle aree
dei singoli rettangoli e quindi vale 1.0.</p>
<div id="esercizio-con-r-1" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Esercizio con R</h3>
<p>Poniamoci il problema di costruire un istogramma per i dati del BDI-II.
Nell’istogramma viene rappresentata la frequenza relativa delle classi: l’area di ogni barra dell’istogramma è proporzionale alla frequenza relativa della classe che la barra rappresenta.
Come si trova l’altezza delle barre dell’istogramma? Per la classe [0, 13.5), ad esempio, la frequenza relativa è 36/66. Tale valore corrisponde all’<strong>area</strong> del rettangolo. Dato che la base del rettangolo è 13.5, l’altezza sarà 36/66 / 13.5, ovvero {r 36/66 / 13.5}. E così via per le altre barre dell’istogramma.</p>
<p>Una rappresentazione grafica dell’istogramma delle frequenze relative si può ottenere con R utilizzando le funzioni di <code>ggplot2</code>.
Il pacchetto <code>ggplot2</code> è un potente strumento per rappresentare graficamente i dati. Le iniziali del nome, <code>gg</code>, si riferiscono alla ‘’Grammar of Graphics’’, che è un modo di pensare le figure come una serie di layer stratificati. Originariamente descritta da Leland Wilkinson, la grammatica dei grafici è stata aggiornata e applicata in R da Hadley Wickham, il creatore del pacchetto. Per chiarezza, precisiamo che la funzione <code>ggplot()</code> utilizza intervalli aperti a destra.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="chapter-descriptive-stats.html#cb15-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> bysubj <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="chapter-descriptive-stats.html#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> bdi)) <span class="sc">+</span></span>
<span id="cb15-3"><a href="chapter-descriptive-stats.html#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb15-4"><a href="chapter-descriptive-stats.html#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> ..density..),</span>
<span id="cb15-5"><a href="chapter-descriptive-stats.html#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">13.5</span>, <span class="fl">19.5</span>, <span class="fl">28.5</span>, <span class="fl">44.1</span>) <span class="co"># il valore BDI-II massimo è 44</span></span>
<span id="cb15-6"><a href="chapter-descriptive-stats.html#cb15-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-7"><a href="chapter-descriptive-stats.html#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">13.5</span>, <span class="fl">19.5</span>, <span class="fl">28.5</span>, <span class="fl">44.1</span>)) <span class="sc">+</span></span>
<span id="cb15-8"><a href="chapter-descriptive-stats.html#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-9"><a href="chapter-descriptive-stats.html#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;BDI-II&quot;</span>,</span>
<span id="cb15-10"><a href="chapter-descriptive-stats.html#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densità di frequenza&quot;</span></span>
<span id="cb15-11"><a href="chapter-descriptive-stats.html#cb15-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-12"><a href="chapter-descriptive-stats.html#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_apa</span>()</span>
<span id="cb15-13"><a href="chapter-descriptive-stats.html#cb15-13" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div>
<div class="figure"><span id="fig:hist1zetsche"></span>
<img src="Psicometria_files/figure-html/hist1zetsche-1.png" alt="Istogramma per i valori BDI-II riportati da @zetsche_future_2019." width="80%" />
<p class="caption">
Figura 4.1: Istogramma per i valori BDI-II riportati da <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>.
</p>
</div>
<p>Con i quattro intervalli individuati dai cut-off del BDI-II otteniamo la
rappresentazione riportata nella figura <a href="chapter-descriptive-stats.html#fig:hist1zetsche">4.1</a>. Nel caso della prima barra dell’istogramma a sinistra, l’ampiezza dell’intervallo è pari a 13.5 e
l’area della barra (ovvero, la frequenza relativa) è uguale a 36/66.
Dunque l’altezza della barra è uguale a (36 / 66) / 13.5 = 0.040. Lo
stesso procedimento si applica per il calcolo dell’altezza degli altri
rettangoli.</p>
<p>Anche se nel caso presente è sensato usare ampiezze diverse per gli intervalli delle classi, in generale gli istogrammi si costruiscono utilizzando intervalli riportati sulle ascisse con un’ampiezza uguale.
Questo è il caso dell’istogramma seguente il quale è stato generato a partire dagli stessi dati.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="chapter-descriptive-stats.html#cb16-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> bysubj <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="chapter-descriptive-stats.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> bdi)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="chapter-descriptive-stats.html#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb16-4"><a href="chapter-descriptive-stats.html#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> ..density..),</span>
<span id="cb16-5"><a href="chapter-descriptive-stats.html#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">44.1</span>, <span class="at">length.out =</span> <span class="dv">7</span>)</span>
<span id="cb16-6"><a href="chapter-descriptive-stats.html#cb16-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-7"><a href="chapter-descriptive-stats.html#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="fl">0.00</span>,  <span class="fl">7.35</span>, <span class="fl">14.70</span>, <span class="fl">22.05</span>, <span class="fl">29.40</span>, <span class="fl">36.75</span>, <span class="fl">44.10</span>)) <span class="sc">+</span></span>
<span id="cb16-8"><a href="chapter-descriptive-stats.html#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-9"><a href="chapter-descriptive-stats.html#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;BDI-II&quot;</span>,</span>
<span id="cb16-10"><a href="chapter-descriptive-stats.html#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densità di frequanza&quot;</span></span>
<span id="cb16-11"><a href="chapter-descriptive-stats.html#cb16-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-12"><a href="chapter-descriptive-stats.html#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_apa</span>()</span>
<span id="cb16-13"><a href="chapter-descriptive-stats.html#cb16-13" aria-hidden="true" tabindex="-1"></a>p2</span></code></pre></div>
<div class="figure"><span id="fig:hist2zetsche"></span>
<img src="Psicometria_files/figure-html/hist2zetsche-1.png" alt="Una rappresentazione più comune per l'istogramma dei valori BDI-II di @zetsche_future_2019 nella quale gli intervalli delle classi hanno ampiezze uguali." width="80%" />
<p class="caption">
Figura 4.2: Una rappresentazione più comune per l’istogramma dei valori BDI-II di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span> nella quale gli intervalli delle classi hanno ampiezze uguali.
</p>
</div>
</div>
</div>
<div id="funzione-di-densità-empirica" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Funzione di densità empirica</h2>
<p>Il confronto tra le figure <a href="chapter-descriptive-stats.html#fig:hist1zetsche">4.1</a> e <a href="chapter-descriptive-stats.html#fig:hist2zetsche">4.2</a> rende chiaro un limite degli istogrammi. È infatti ovvio che il profilo dell’istogramma è arbitrario: a seconda del numero e dei limiti delle classi che vengono scelte,
cambiano sia il numero che la forma delle barre dell’istogramma. Questo rende difficile fornire un’interpretazione alle informazioni fornite da un istogramma.</p>
<p>Il problema precedente può essere alleviato utilizzando una
rappresentazione alternativa della distribuzione di frequenza, ovvero la
stima della densità della frequenza dei dati (detta anche stima <em>kernel
di densità</em>). Un modo semplice per pensare a tale rappresentazione, che
in inglese va sotto il nome di <em>density plot</em>, è quello di immaginare un
grande campione di dati, in modo che diventi possibile definire un
enorme numero di classi di equivalenza di ampiezza molto piccola, le
quali non risultino vuote. In tali circostanze, la funzione di densità
empirica non è altro che il profilo <em>lisciato</em> dell’istogramma. La
stessa idea si applica anche quando il campione è più piccolo.</p>
<div id="esercizio-con-r-2" class="section level3" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Esercizio con R</h3>
<p>Nel caso dei dati del BDI-II otteniamo la reppresentazione fornita dalla figura seguente.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="chapter-descriptive-stats.html#cb17-1" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> bysubj <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="chapter-descriptive-stats.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> bdi)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="chapter-descriptive-stats.html#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb17-4"><a href="chapter-descriptive-stats.html#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> ..density..), </span>
<span id="cb17-5"><a href="chapter-descriptive-stats.html#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">44.1</span>, <span class="at">length.out =</span> <span class="dv">7</span>)</span>
<span id="cb17-6"><a href="chapter-descriptive-stats.html#cb17-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb17-7"><a href="chapter-descriptive-stats.html#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(</span>
<span id="cb17-8"><a href="chapter-descriptive-stats.html#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> bdi), </span>
<span id="cb17-9"><a href="chapter-descriptive-stats.html#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">adjust =</span> <span class="fl">0.5</span>, </span>
<span id="cb17-10"><a href="chapter-descriptive-stats.html#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">0.8</span>, </span>
<span id="cb17-11"><a href="chapter-descriptive-stats.html#cb17-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;steelblue3&quot;</span>, </span>
<span id="cb17-12"><a href="chapter-descriptive-stats.html#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span></span>
<span id="cb17-13"><a href="chapter-descriptive-stats.html#cb17-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb17-14"><a href="chapter-descriptive-stats.html#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb17-15"><a href="chapter-descriptive-stats.html#cb17-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;BDI-II&quot;</span>,</span>
<span id="cb17-16"><a href="chapter-descriptive-stats.html#cb17-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densità di frequenza&quot;</span></span>
<span id="cb17-17"><a href="chapter-descriptive-stats.html#cb17-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb17-18"><a href="chapter-descriptive-stats.html#cb17-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_apa</span>()</span>
<span id="cb17-19"><a href="chapter-descriptive-stats.html#cb17-19" aria-hidden="true" tabindex="-1"></a>p3</span></code></pre></div>
<div class="figure"><span id="fig:zetschehist3"></span>
<img src="Psicometria_files/figure-html/zetschehist3-1.png" alt="Funzione di densità empirica per i valori BDI-II di @zetsche_future_2019." width="80%" />
<p class="caption">
Figura 4.3: Funzione di densità empirica per i valori BDI-II di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>.
</p>
</div>
<p>Che interpretazione possiamo attribuire alla funzione di densità empirica rappresentata nella figura <a href="chapter-descriptive-stats.html#fig:zetschehist3">4.3</a>?
La interpretiamo come abbiamo fatto con gli istogrammi: l’area sottesa al grafico della funzione di densità empirica in un certo intervallo rappresenta la proporzione dei casi della distribuzione che hanno valori compresi nell’intervallo considerato.</p>
</div>
</div>
<div id="forma-di-una-distribuzione" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Forma di una distribuzione</h2>
<p>In generale, la forma di una distribuzione descrive come i dati si
distribuiscono intorno ai valori centrali. Distinguiamo tra
distribuzioni simmetriche e asimmetriche, e tra distribuzioni unimodali
o multimodali. Un’illustrazione grafica è fornita nella
figura seguente.</p>
<div class="figure"><span id="fig:unnamed-chunk-13"></span>
<img src="Psicometria_files/figure-html/unnamed-chunk-13-1.png" alt="1: Asimmetria negativa. 2: Asimmetria positiva. 3: Distribuzione unimodale. 4: Distribuzione bimodale." width="672" />
<p class="caption">
Figura 4.4: 1: Asimmetria negativa. 2: Asimmetria positiva. 3: Distribuzione unimodale. 4: Distribuzione bimodale.
</p>
</div>
<p>Nel pannello 1 la distribuzione è unimodadle con asimmetria negativa; nel pannello 2 la distribuzione è unimodadle con asimmetria positiva; nel pannello 3 la distribuzione è simmetrica e unimodale; nel pannello 4 la distribuzione è bimodale.</p>
<p>Se consideriamo nuovamente la figura <a href="chapter-descriptive-stats.html#fig:zetschehist3">4.3</a> possiamo dire che la distribuzione dei valori del BDI-II nel campione considerato da <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span> è bimodale.</p>
</div>
<div id="indici-di-posizione" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Indici di posizione</h2>
<div id="quantili" class="section level3" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> Quantili</h3>
<p>La descrizione della distribuzione dei valori BDI-II di
<span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span> può essere facilitata dalla determinazione di
alcuni valori caratteristici che sintetizzano le informazioni contenute
nella distribuzione di frequenze. Si dicono <em>quantili</em> (o <em>frattili</em>)
quei valori caratteristici che hanno le seguenti proprietà. I <em>quartili</em>
sono quei valori che ripartiscono i dati <span class="math inline">\(x_i\)</span> in quattro parti
ugualmente numerose (pari ciascuna al 25% del totale). Il primo
quartile, <span class="math inline">\(q_1\)</span>, lascia alla sua sinistra il 25% del campione pensato
come una fila ordinata (a destra quindi il 75%). Il secondo quartile
<span class="math inline">\(q_2\)</span> lascia a sinistra il 50% del campione (a destra quindi il 50%).
Esso viene anche chiamato <em>mediana</em>. Il terzo quartile lascia a sinistra
il 75% del campione (a destra quindi il 25%). Secondo lo stesso
criterio, si dicono <em>decili</em> i quantili di ordine <span class="math inline">\(p\)</span> multiplo di 0.10 e
<em>percentili</em> i quantili di ordine <span class="math inline">\(p\)</span> multiplo di 0.01.</p>
<p>Come si calcolano i quantili? Consideriamo la definizione di quantile
<em>non interpolato</em> di ordine <span class="math inline">\(p\)</span> <span class="math inline">\((0 &lt; p &lt; 1)\)</span>. Si procede innanzitutto
ordinando i dati in ordine crescente, <span class="math inline">\(\{x_1, x_2, \dots, x_n\}\)</span>. Ci
sono poi due possibilità. Se il valore <span class="math inline">\(np\)</span> non è intero, sia <span class="math inline">\(k\)</span>
l’intero tale che <span class="math inline">\(k &lt; np &lt; k + 1\)</span> – ovvero, la parte intera di <span class="math inline">\(np\)</span>.
Allora <span class="math inline">\(q_p = x_{k+1}.\)</span> Se <span class="math inline">\(np = k\)</span> con <span class="math inline">\(k\)</span> intero, allora
<span class="math inline">\(q_p = \frac{1}{2}(x_{k} + x_{k+1}).\)</span> Se vogliamo calcolare il primo
quartile <span class="math inline">\(q_1\)</span>, ad esempio, utilizziamo <span class="math inline">\(p = 0.25\)</span>. Dovendo calcolare
gli altri quantili basta sostituire a <span class="math inline">\(p\)</span> il valore appropriato[^2].</p>
<p>Gli indici di posizione, tra le altre cose, hanno un ruolo importante,
ovvero vengono utilizzati per creare una rappresentazione grafica di una
distribuzione di valori che è molto popolare e può essere usata in
alternativa ad un istogramma (in realtà vedremo poi come possa essere
combinata con un istogramma). Tale rappresentazione va sotto il nome di
box-plot.</p>
<p>Per fare un esempio, consideriamo i nove soggetti del campione clinico di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span> che hanno riportato un unico episodio di depressione maggiore. Per tali soggetti i valori ordinati del BDI-II (per semplicità li chiameremo <span class="math inline">\(x\)</span>) sono i seguenti: 19, 26, 27, 28, 28, 33, 33, 41, 43.
Per il calcolo del secondo quartile (non interpolato), ovvero per il calcolo della mediana, dobbiamo considerare la quantità <span class="math inline">\(np = 9 \cdot 0.5 = 4.5\)</span>, non intero. Quindi, <span class="math inline">\(q_1 = x_{4 + 1} = 27\)</span>.
Per il calcolo del quantile (non interpolato) di ordine <span class="math inline">\(p = 2/3\)</span> dobbiamo considerare la quantità <span class="math inline">\(np = 9 \cdot 2/3 = 6\)</span>, intero. Quindi, <span class="math inline">\(q_{\frac{2}{3}} = \frac{1}{2} (x_{6} + x_{7}) = \frac{1}{2} (33 + 33) = 33\)</span>.</p>
</div>
<div id="box-plot" class="section level3" number="4.6.2">
<h3><span class="header-section-number">4.6.2</span> Box-plot</h3>
<p>Il <em>box-plot</em> (o diagramma a scatola) è uno strumento grafico utile al
fine di ottenere informazioni circa la dispersione e l’eventuale
simmetria o asimmetria di una distribuzione. Per costruire un box-plot
si rappresenta sul piano cartesiano un rettangolo (cioè la “scatola”) di
altezza arbitraria la cui base corrisponde alla dist intanza
interquartile (IQR = <span class="math inline">\(q_{0.75} - q_{0.25}\)</span>). La linea interna alla
scatola rappresenta la mediana <span class="math inline">\(q_{0.5}\)</span>. Si tracciano poi ai lati della
scatola due segmenti di retta i cui estremi sono detti “valore
adiacente” inferiore e superiore. Il valore adiacente inferiore è il
valore più piccolo tra le osservazioni che risulta maggiore o uguale al
primo quartile meno la distanza corrispondente a 1.5 volte la distanza
interquartile.
Il valore adiacente superiore è il valore più grande tra le osservazioni che risulta minore o uguale a <span class="math inline">\(Q_3+1.5\)</span> IQR. I valori esterni ai valori adiacenti (chiamati <em>valori anomali</em>) vengono rappresentati individualmente nel box-plot per meglio evidenziarne la presenza e la posizione.</p>
<div class="figure"><span id="fig:unnamed-chunk-14"></span>
<img src="Psicometria_files/figure-html/unnamed-chunk-14-1.png" alt="Box-plot, laddove $M$ è la mediana, $ar{x}$ è la media aritmetica e IQR è la distanza interquartile ($Q_3 - Q_1$)." width="672" />
<p class="caption">
Figura 4.5: Box-plot, laddove <span class="math inline">\(M\)</span> è la mediana, <span class="math inline">\(ar{x}\)</span> è la media aritmetica e IQR è la distanza interquartile (<span class="math inline">\(Q_3 - Q_1\)</span>).
</p>
</div>
<p>Consideriamo ora un caso concreto nel quale viene utilizzato un box-plot.
Nel caso dei dati di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span> ci chiediamo in che modo si differenziano le distribuzioni del BDI-II tra i due gruppi considerati, ovvero tra il gruppo dei pazienti e il gruppo di controllo.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="chapter-descriptive-stats.html#cb18-1" aria-hidden="true" tabindex="-1"></a>bysubj <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="chapter-descriptive-stats.html#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(esm_id, group) <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="chapter-descriptive-stats.html#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb18-4"><a href="chapter-descriptive-stats.html#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">bdi =</span> <span class="fu">mean</span>(bdi),</span>
<span id="cb18-5"><a href="chapter-descriptive-stats.html#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">nr_of_episodes =</span> <span class="fu">mean</span>(nr_of_episodes, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-6"><a href="chapter-descriptive-stats.html#cb18-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb18-7"><a href="chapter-descriptive-stats.html#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;esm_id&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="chapter-descriptive-stats.html#cb20-1" aria-hidden="true" tabindex="-1"></a>bysubj <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="chapter-descriptive-stats.html#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>group, <span class="at">y=</span>bdi)) <span class="sc">+</span> </span>
<span id="cb20-3"><a href="chapter-descriptive-stats.html#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb20-4"><a href="chapter-descriptive-stats.html#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-5"><a href="chapter-descriptive-stats.html#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Gruppo&quot;</span>,</span>
<span id="cb20-6"><a href="chapter-descriptive-stats.html#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;BDI-II&quot;</span></span>
<span id="cb20-7"><a href="chapter-descriptive-stats.html#cb20-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-8"><a href="chapter-descriptive-stats.html#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_apa</span>()</span></code></pre></div>
<p><img src="Psicometria_files/figure-html/unnamed-chunk-15-1.png" width="80%" /></p>
<p>La figura <a href="chapter-descriptive-stats.html#fig:violin-zetsche">4.6</a> fornisce due rappresentazioni grafiche che possono essere utilizzate per rispondere a questa domanda.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="chapter-descriptive-stats.html#cb21-1" aria-hidden="true" tabindex="-1"></a>bysubj <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="chapter-descriptive-stats.html#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(esm_id, group) <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="chapter-descriptive-stats.html#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-4"><a href="chapter-descriptive-stats.html#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">bdi =</span> <span class="fu">mean</span>(bdi),</span>
<span id="cb21-5"><a href="chapter-descriptive-stats.html#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">nr_of_episodes =</span> <span class="fu">mean</span>(nr_of_episodes, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-6"><a href="chapter-descriptive-stats.html#cb21-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb21-7"><a href="chapter-descriptive-stats.html#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;esm_id&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="chapter-descriptive-stats.html#cb23-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> bysubj <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="chapter-descriptive-stats.html#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>group, <span class="at">y=</span>bdi)) <span class="sc">+</span> </span>
<span id="cb23-3"><a href="chapter-descriptive-stats.html#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">trim=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb23-4"><a href="chapter-descriptive-stats.html#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_dotplot</span>(<span class="at">binaxis=</span><span class="st">&#39;y&#39;</span>, <span class="at">stackdir=</span><span class="st">&#39;center&#39;</span>, <span class="at">dotsize=</span><span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="chapter-descriptive-stats.html#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb23-6"><a href="chapter-descriptive-stats.html#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Gruppo&quot;</span>,</span>
<span id="cb23-7"><a href="chapter-descriptive-stats.html#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;BDI-II&quot;</span></span>
<span id="cb23-8"><a href="chapter-descriptive-stats.html#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">#, caption = &quot;Fonte: Zetsche, Buerkner, &amp; Renneberg (2020)&quot;</span></span>
<span id="cb23-9"><a href="chapter-descriptive-stats.html#cb23-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb23-10"><a href="chapter-descriptive-stats.html#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_apa</span>()</span>
<span id="cb23-11"><a href="chapter-descriptive-stats.html#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="chapter-descriptive-stats.html#cb23-12" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> bysubj <span class="sc">%&gt;%</span> </span>
<span id="cb23-13"><a href="chapter-descriptive-stats.html#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>group, <span class="at">y=</span>bdi)) <span class="sc">+</span> </span>
<span id="cb23-14"><a href="chapter-descriptive-stats.html#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">trim=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb23-15"><a href="chapter-descriptive-stats.html#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.05</span>) <span class="sc">+</span></span>
<span id="cb23-16"><a href="chapter-descriptive-stats.html#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb23-17"><a href="chapter-descriptive-stats.html#cb23-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Gruppo&quot;</span>,</span>
<span id="cb23-18"><a href="chapter-descriptive-stats.html#cb23-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;BDI-II&quot;</span></span>
<span id="cb23-19"><a href="chapter-descriptive-stats.html#cb23-19" aria-hidden="true" tabindex="-1"></a>    <span class="co">#, caption = &quot;Fonte: Zetsche, Buerkner, &amp; Renneberg (2020)&quot;</span></span>
<span id="cb23-20"><a href="chapter-descriptive-stats.html#cb23-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb23-21"><a href="chapter-descriptive-stats.html#cb23-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_apa</span>()</span>
<span id="cb23-22"><a href="chapter-descriptive-stats.html#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="chapter-descriptive-stats.html#cb23-23" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> p2</span></code></pre></div>
<pre><code>## `stat_bindot()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<div class="figure"><span id="fig:violin-zetsche"></span>
<img src="Psicometria_files/figure-html/violin-zetsche-1.png" alt="Due versioni di un violin plot per i valori BDI-II di ciascuno dei due gruppi di soggetti esaminati da @zetsche_future_2019." width="95%" />
<p class="caption">
Figura 4.6: Due versioni di un violin plot per i valori BDI-II di ciascuno dei due gruppi di soggetti esaminati da <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>.
</p>
</div>
<p>Nella figura <a href="chapter-descriptive-stats.html#fig:violin-zetsche">4.6</a> sinistra sono rappresentati i dati grezzi: questa è la pratica migliore quando il numero di osservazioni è piccolo. La linea curva che circonda (simmetricamente) le osservazioni è l’<strong>istogramma lisciato</strong> che abbiamo descritto in precedenza. Nella figura <a href="chapter-descriptive-stats.html#fig:violin-zetsche">4.6</a> destra sono rappresentanti gli stessi dati: la funzione di densità empirica è la stessa di prima, ma al suo interno viene collocato un box-plot. Questa seconda rappresentazione è da preferirsi quando ci sono molte osservazioni e non è utile rappresentare singolarmente ciascun dato. Entrambe le rappresentazioni suggeriscono che la distribuzione dei dati è all’incirca simmetrica nel gruppo clinico (codificato come <code>mdd</code>). Il gruppo di controllo (<code>ctl</code>) mostra invece un’asimmetria positiva, con tre osservazioni evidenziate nel boxplot come dei “valori anomali,” dato che si discostano dalla mediana di una quantità maggiore di 1.5 IQR.</p>
</div>
<div id="leccellenza-grafica" class="section level3" number="4.6.3">
<h3><span class="header-section-number">4.6.3</span> L’eccellenza grafica</h3>
<p>Non c’è un modo “corretto” per rappresentare in forma grafica un insieme
di dati. Ciascuno dei grafici che abbiamo discusso ha i suoi pregi e i
suoi difetti. Un ricercatore che ha influenzato molto il modo in cui
viene realizzata la visualizzazione dei dati scientifici è Edward Tufte,
soprannominato dal New York Times il “Leonardo da Vinci dei dati.”
Secondo Tufte, “l’eccellenza nella grafica consiste nel comunicare idee
complesse in modo chiaro, preciso ed efficiente.” Nella visualizzazione
delle informazioni, l’“eccellenza grafica” ha l’obiettivo di comunicare
al lettore il maggior numero di idee nel minor tempo possibile, con meno
inchiostro possibile, usando il minor spazio possibile. Secondo
<span class="citation"><a href="bibliografia.html#ref-tufte_visual_display" role="doc-biblioref">Tufte</a> (<a href="bibliografia.html#ref-tufte_visual_display" role="doc-biblioref">2001</a>)</span>, le rappresentazioni grafiche dovrebbero:</p>
<ol style="list-style-type: decimal">
<li>mostrare i dati;</li>
<li>indurre l’osservatore a riflettere sulla sostanza piuttosto che
sulla progettazione grafica, o qualcos’altro;</li>
<li>evitare di distorcere quanto i dati stanno comunicando (“integrità
grafica”);</li>
<li>presentare molte informazioni in forma succinta;</li>
<li>rivelare la coerenza tra le molte dimensioni dei dati;</li>
<li>incoraggiare l’osservatore a comparare differenti porzioni di dati;</li>
<li>rivelare i dati a diversi livelli di dettaglio, da una visione ampia
alla struttura di base;</li>
<li>servire ad uno scopo preciso (descrizione, esplorazione, o la
risposta a qualche domanda);</li>
<li>essere fortemente integrate con le descrizioni statistiche e verbali
dei dati fornite nel testo.</li>
</ol>
<p>In base a questi principi, la funzione di densità empirica fornisce una
rappresentazione migliore dei dati di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span> di quanto lo faccia un istogramma. Inoltre, se oltre al grupppo di appartenenza non ci sono altre dimensioni importanti da mettere in evidenza, allora la nostra scelta dovrebbe
ricadere sul pannello di sinistra della figura <a href="chapter-descriptive-stats.html#fig:violin-zetsche">4.6</a>.</p>
</div>
</div>
<div id="indici-di-tendenza-centrale" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Indici di tendenza centrale</h2>
<p>L’analisi grafica, esaminata in precedenza, costituisce la base di
partenza di qualsivoglia analisi quantitativa dei dati. Tramite
l’analisi grafica possiamo capire alcune caratteristiche importanti di
una distribuzione: per esempio, se è simmetrica o asimmetrica; oppure se
è unimodale o multimodale. Successivamente, possiamo calcolare degli
indici numerici che descrivono in modo sintetico le caratteristiche di
base dei dati esaminati. Tra le misure di tendenza centrale, ovvero tra
gli indici che forniscono un’idea dei valori attorno ai quali sono
prevalentemente concentrati i dati di un campione, quella più
comunemente usata è la media.</p>
<div id="media" class="section level3" number="4.7.1">
<h3><span class="header-section-number">4.7.1</span> Media</h3>
<p>Tutti conosciamo la media aritmetica di <span class="math inline">\(\{x_1, x_2, \dots, x_n\}\)</span>,
ovvero il numero reale <span class="math inline">\(\bar{x}\)</span> definito da
<span class="math display" id="eq:mean">\[\begin{equation}
\bar{x}=\frac{1}{n}\sum_{i=1}^n x_i.
\tag{4.1}
\end{equation}\]</span>
Nell’eq. <a href="chapter-descriptive-stats.html#eq:mean">(4.1)</a> abbiamo usato la notazione delle sommatorie
per descrivere una somma di valori. Questa notazione è molto usata in
statistica e viene descritta in Appendice.</p>
<p>La media gode della seguente importante proprietà: la somma degli scarti
tra ciascuna modalità <span class="math inline">\(x_i\)</span> e la media aritmetica <span class="math inline">\(\bar{x}\)</span> è nulla,
cioè
<span class="math display">\[
\sum_{i=1}^n (x_i - \bar{x}) = 0.\notag
\label{eq:diffmeansumzero}\]</span> Infatti, <span class="math display">\[\begin{aligned}
\sum_{i=1}^n (x_i - \bar{x}) &amp;= \sum_i x_i - \sum_i \bar{x}\notag\\
&amp;= \sum_i x_i - n \bar{x}\notag\\
&amp;= \sum_i x_i - \sum_i x_i = 0.\notag\end{aligned}
\]</span></p>
<p>Ciò ci consente di pensare alla media come al baricentro della distribuzione.</p>
<p>Un’altra proprietà della media è la seguente. La somma dei quadrati
degli scarti tra ciascuna modalità <span class="math inline">\(x_i\)</span> e una costante arbitraria
<span class="math inline">\(a \in \Re\)</span>, cioè <span class="math display">\[\varphi(a) = \sum_{i=1}^n (x_i - a)^2,\notag\]</span> è
minima per <span class="math inline">\(a = \bar{x}\)</span>.</p>
<p>Il concetto statistico di media ha suscitato molte battute. Per esempio,
il fatto che, in media, ciascuno di noi ha un numero di gambe circa pari
a 1.9999999. Oppure, il fatto che, in media, ciascuno di noi ha un
testicolo. Ma la media ha altri problemi, oltre al fatto di ispirare
battute simili alle precedenti. In particolare, dobbiamo notare che la
media non è sempre l’indice che meglio rappresenta la tendenza centrale
di una distribuzione. In particolare, ciò non accade quando la
distribuzione è asimmetrica, o in presenza di valori anomali (<em>outlier</em>)
– si veda il pannello di destra della figura <a href="chapter-descriptive-stats.html#fig:violin-zetsche">4.6</a>. In tali circostanze, la tendenza centrale della distribuzione è meglio rappresentata dalla mediana o dalla media spuntata.</p>
<div id="esercizio-con-r-3" class="section level4" number="4.7.1.1">
<h4><span class="header-section-number">4.7.1.1</span> Esercizio con R</h4>
<p>Calcoliamo la media dei valori BDI-II per i due gruppi di soggetti di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="chapter-descriptive-stats.html#cb25-1" aria-hidden="true" tabindex="-1"></a>bysubj <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="chapter-descriptive-stats.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="chapter-descriptive-stats.html#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb25-4"><a href="chapter-descriptive-stats.html#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_bdi =</span> <span class="fu">mean</span>(bdi)</span>
<span id="cb25-5"><a href="chapter-descriptive-stats.html#cb25-5" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   group avg_bdi
##   &lt;fct&gt;   &lt;dbl&gt;
## 1 ctl      1.69
## 2 mdd     30.9</code></pre>
</div>
</div>
<div id="media-spuntata" class="section level3" number="4.7.2">
<h3><span class="header-section-number">4.7.2</span> Media spuntata</h3>
<p>La <em>media spuntata</em> <span class="math inline">\(\bar{x}_t\)</span> (<em>trimmed mean</em>) non è altro che la
media dei dati calcolata considerando solo il 90% (o altra percentuale)
dei dati centrali. Per calcolare <span class="math inline">\(\bar{x}_t\)</span> si ordinando i dati secondo
una sequenza crescente, <span class="math inline">\(x_1 \leq x_2 \leq x_3 \leq \dots \leq x_n\)</span>, per
poi eliminare il primo 5% e l’ultimo 5% dei dati della serie così
ordinata. La media spuntata è data dalla media aritmetica dei dati rimanenti.</p>
<div id="esercizio-con-r-4" class="section level4" number="4.7.2.1">
<h4><span class="header-section-number">4.7.2.1</span> Esercizio con R</h4>
<p>Calcoliamo la media spuntata dei valori BDI-II per i due gruppi di soggetti di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span> escludendo il 10% dei valori più estremi in ciascun gruppo.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="chapter-descriptive-stats.html#cb28-1" aria-hidden="true" tabindex="-1"></a>bysubj <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="chapter-descriptive-stats.html#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb28-3"><a href="chapter-descriptive-stats.html#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb28-4"><a href="chapter-descriptive-stats.html#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_trim_bdi =</span> <span class="fu">mean</span>(bdi, <span class="at">trim =</span> <span class="fl">0.1</span>)</span>
<span id="cb28-5"><a href="chapter-descriptive-stats.html#cb28-5" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   group avg_trim_bdi
##   &lt;fct&gt;        &lt;dbl&gt;
## 1 ctl            1  
## 2 mdd           30.6</code></pre>
</div>
</div>
<div id="moda-e-mediana" class="section level3" number="4.7.3">
<h3><span class="header-section-number">4.7.3</span> Moda e mediana</h3>
<p>In precedenza abbiamo già incontrato altri due popolari indici di
tendenza centrale: la <em>moda</em> (<em>Mo</em>), ovvero il valore centrale della
classe con la frequenza massima (può succedere che una distribuzione
abbia più mode; in tal caso si dice <em>multimodale</em> e questo operatore
perde il suo significato di indice di tendenza centrale) e la <em>mediana</em>
<span class="math inline">\(\tilde{x}\)</span>.</p>
<div id="esercizio-con-r-5" class="section level4" number="4.7.3.1">
<h4><span class="header-section-number">4.7.3.1</span> Esercizio con R</h4>
<p>Calcoliamo i quantili di ordine 0.25, 0.5 e 0.75 dei valori BDI-II per i due gruppi di soggetti di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="chapter-descriptive-stats.html#cb31-1" aria-hidden="true" tabindex="-1"></a>bysubj <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="chapter-descriptive-stats.html#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb31-3"><a href="chapter-descriptive-stats.html#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb31-4"><a href="chapter-descriptive-stats.html#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">q25 =</span> <span class="fu">quantile</span>(bdi, <span class="at">probs =</span> <span class="fl">0.25</span>),</span>
<span id="cb31-5"><a href="chapter-descriptive-stats.html#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">q50 =</span> <span class="fu">quantile</span>(bdi, <span class="at">probs =</span> <span class="fl">0.50</span>),</span>
<span id="cb31-6"><a href="chapter-descriptive-stats.html#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">q75 =</span> <span class="fu">quantile</span>(bdi, <span class="at">probs =</span> <span class="fl">0.75</span>)</span>
<span id="cb31-7"><a href="chapter-descriptive-stats.html#cb31-7" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 4
##   group   q25   q50   q75
##   &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 ctl       0     1     2
## 2 mdd      26    30    35</code></pre>

<div class="remark">
 <span class="remark"><em>Osservazione. </em></span> Si noti che solitamente i software restituiscono un valore <strong>interpolato</strong> del <span class="math inline">\(p\)</span>-esimo quantile <span class="math inline">\(q_p\)</span> <span class="math inline">\((0 &lt; p &lt; 1)\)</span>, il quale viene calcolato mediante specifiche procedure. Il risultato fornito dai software, dunque, non sarà identico a quello trovato utilizzando la definizione non interpolata di quantile che abbiamo presentato qui. Se, per qualche ragione, vogliamo conoscere l’algoritmo usato per la determinazione dei quantili interpolati, dobbiamo leggere la documentazione del software.
</div>
</div>
</div>
</div>
<div id="indici-di-dispersione" class="section level2" number="4.8">
<h2><span class="header-section-number">4.8</span> Indici di dispersione</h2>
<p>Le medie e gli indici di posizione descritti in precedenza forniscono
delle sintesi dei dati che mettono in evidenza la tendenza centrale
delle osservazioni. Tali indici, tuttavia, non considerano un aspetto
importante della distribuzione dei dati, ovvero la variabilità dei
valori numerici della variabile statistica. È dunque necessario
sintetizzare la distribuzione di una variabile statistica oltre che con
le misure di posizione anche tramite l’utilizzo di indicatori che
valutino la dispersione delle unità statistice.</p>
<div id="indici-basati-sullordinamento-dei-dati" class="section level3" number="4.8.1">
<h3><span class="header-section-number">4.8.1</span> Indici basati sull’ordinamento dei dati</h3>
<p>È possibile calcolare degli indici di variabilità basati
sull’ordinamento dei dati. L’indice più ovvio è l’intervallo di
variazione, ovvero la distanza tra il valore massimo e il valore minimo
di una distribuzione di modalità, mentre in precedenza abbiamo già
incontrato la differenza interquartile. Questi due indici, però, hanno
il limite di essere calcolati sulla base di due soli valori della
distribuzione (<span class="math inline">\(x_{\text{max}}\)</span> e <span class="math inline">\(x_{\text{mini}}\)</span>, oppure <span class="math inline">\(x_{0.25}\)</span> e
<span class="math inline">\(x_{0.75}\)</span>). Pertanto non utilizzano tutte le informazioni che sono
disponibili. Inoltre, l’intervallo di variazione ha il limite di essere
pesantemente influenzato dalla presenza di valori anomali.</p>
</div>
<div id="scostamento-medio-semplice-dalla-media" class="section level3" number="4.8.2">
<h3><span class="header-section-number">4.8.2</span> Scostamento medio semplice dalla media</h3>
<p>Dati i limiti delle statistiche precedenti è più comune misurare la
variabilità di una variabile statistica come la dispersione dei dati
attorno ad un indice di tendenza centrale. Scelto l’indice di tendenza
centrale rispetto al quale si vuole misurare la dispersione, è possibile
poi calcolare la media degli scostamenti dei singoli dati dal valore di
riferimento. Ad esempio, se scegliamo la mediana quale misura di
posizione centrale, è possibile calcolare la media aritmetica della
distribuzione degli scarti in valore assoluto tra ciascuna modalità e la
mediana stessa. Nel caso di una variabile statistica <span class="math inline">\(X\)</span> lo <em>scostamento
medio semplice dalla media</em> è la quantità</p>
<p><span class="math display" id="eq:scost-sempl-mediana">\[\begin{equation}
S_{Me} = \frac{1}{n} \sum_{i=1}^n |x_i - x_{0.5}|.
\tag{4.2}
\end{equation}\]</span></p>
<div id="esercizio-con-r-6" class="section level4" number="4.8.2.1">
<h4><span class="header-section-number">4.8.2.1</span> Esercizio con R</h4>
<p>Calcoliamo lo scostamento medio semplice dalla media per il BDI-II dei due gruppi di soggetti di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="chapter-descriptive-stats.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(bysubj<span class="sc">$</span>bdi <span class="sc">-</span> <span class="fu">median</span>(bysubj<span class="sc">$</span>bdi)))</span></code></pre></div>
<pre><code>## [1] 14.48387</code></pre>
<p>Oppure, per i due gruppi:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="chapter-descriptive-stats.html#cb36-1" aria-hidden="true" tabindex="-1"></a>mean_abs_dev <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb36-2"><a href="chapter-descriptive-stats.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(<span class="fu">abs</span>(x <span class="sc">-</span> <span class="fu">median</span>(x)))</span>
<span id="cb36-3"><a href="chapter-descriptive-stats.html#cb36-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb36-4"><a href="chapter-descriptive-stats.html#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="chapter-descriptive-stats.html#cb36-5" aria-hidden="true" tabindex="-1"></a>bysubj <span class="sc">%&gt;%</span> </span>
<span id="cb36-6"><a href="chapter-descriptive-stats.html#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb36-7"><a href="chapter-descriptive-stats.html#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb36-8"><a href="chapter-descriptive-stats.html#cb36-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean_abs_dev =</span> <span class="fu">mean_abs_dev</span>(bdi)</span>
<span id="cb36-9"><a href="chapter-descriptive-stats.html#cb36-9" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   group Mean_abs_dev
##   &lt;fct&gt;        &lt;dbl&gt;
## 1 ctl           1.62
## 2 mdd           5.27</code></pre>
<p>La <em>deviazione mediana assoluta</em> è una misura robusta della dispersione statistica di un campione. Per un insieme <span class="math inline">\(x_1, x_2, \dots, x_n\)</span>, il valore di MAD è definito come la mediana del valore assoluto delle deviazioni dei dati dalla mediana, ovvero:</p>
<p><span class="math display" id="eq:mad">\[\begin{equation}
MAD = \text{med} (|x_i - \text{med}(x_i)|).
\tag{4.3}
\end{equation}\]</span></p>
<p>Per i dati di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span> abbiamo:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="chapter-descriptive-stats.html#cb39-1" aria-hidden="true" tabindex="-1"></a>bysubj <span class="sc">%&gt;%</span> </span>
<span id="cb39-2"><a href="chapter-descriptive-stats.html#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb39-3"><a href="chapter-descriptive-stats.html#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb39-4"><a href="chapter-descriptive-stats.html#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">MAD =</span> <span class="fu">mad</span>(bdi)</span>
<span id="cb39-5"><a href="chapter-descriptive-stats.html#cb39-5" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   group   MAD
##   &lt;fct&gt; &lt;dbl&gt;
## 1 ctl    1.48
## 2 mdd    6.67</code></pre>
</div>
</div>
<div id="varianza" class="section level3" number="4.8.3">
<h3><span class="header-section-number">4.8.3</span> Varianza</h3>
<p>Anche se la statistica definita
dall’eq. <a href="chapter-descriptive-stats.html#eq:scost-sempl-mediana">(4.2)</a> è molto intuitiva, la misura di
variabilità di gran lunga più usata per valutare la variabilità di una
variabile statistica è senza dubbio la varianza. La varianza
<span class="math display" id="eq:var-descr">\[\begin{equation}
s^2 = \frac{1}{n} \sum_{i=1}^n (x_i - \bar{x})^2
\tag{4.4}
\end{equation}\]</span>
è la media dei quadrati degli scarti <span class="math inline">\(x_i - \bar{x}\)</span> tra ogni valore e la media della distribuzione.
La varianza è una misura di dispersione più complessa di quelle esaminate in precedenza. È appropriata solo nel caso di distribuzioni simmetriche e, anch’essa, è fortemente influenzata dai valori anomali. Inoltre, è espressa in
un’unità di misura che è il quadrato dell’unità di misura dei dati originari e quindi ad essa non può essere assegnata un’interpretazione intuitiva.</p>
<div id="esercizio-con-r-7" class="section level4" number="4.8.3.1">
<h4><span class="header-section-number">4.8.3.1</span> Esercizio con R</h4>
<p>Calcoliamo la varianza dei punteggi BDI-II nei due gruppi di soggetti di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="chapter-descriptive-stats.html#cb42-1" aria-hidden="true" tabindex="-1"></a>bysubj <span class="sc">%&gt;%</span> </span>
<span id="cb42-2"><a href="chapter-descriptive-stats.html#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb42-3"><a href="chapter-descriptive-stats.html#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb42-4"><a href="chapter-descriptive-stats.html#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">variance =</span> <span class="fu">var</span>(bdi)</span>
<span id="cb42-5"><a href="chapter-descriptive-stats.html#cb42-5" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   group variance
##   &lt;fct&gt;    &lt;dbl&gt;
## 1 ctl       8.03
## 2 mdd      43.7</code></pre>
</div>
</div>
<div id="deviazione-standard" class="section level3" number="4.8.4">
<h3><span class="header-section-number">4.8.4</span> Deviazione standard</h3>
<p>Per le ragioni espresse sopra, la misura più usata della dispersione di una distribuzione di dati è la <em>deviazione standard</em>, ovvero la radice quadrata della varianza. A differenza della varianza, dunque, la deviazione standard è espressa nella stessa unità di misura dei dati. Come nel caso della varianza, anche la deviazione standard <span class="math inline">\(s\)</span> dovrebbe essere usata soltanto quando la media è adeguata per misurare il centro della distribuzione, ovvero, nel caso di distribuzioni simmetriche. Come nel caso della media <span class="math inline">\(\bar{x}\)</span>, anche la deviazione standard è fortemente influenzata dai dati anomali (<em>outlier</em>), ovvero dalla presenza di uno o di pochi dati che sono molto più distanti dalla media rispetto agli altri valori della distribuzione. Quando tutte le osservazioni sono uguali, <span class="math inline">\(s=0\)</span>, altrimenti <span class="math inline">\(s &gt; 0\)</span>.</p>
<p>Alla deviazione standard può essere assegnata una semplice interpretazione: la deviazione standard è <strong>simile</strong> (ma non identica) allo scostamento medio semplice dalla media. La deviazione standard ci dice, dunque, quanto sono distanti, in media, le singole osservazioni dal centro della distribuzione.</p>
<div id="esercizio-con-r-8" class="section level4" number="4.8.4.1">
<h4><span class="header-section-number">4.8.4.1</span> Esercizio con R</h4>
<p>Calcoliamo la deviazione standard per il BDI-II dei due gruppi di soggetti di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="chapter-descriptive-stats.html#cb45-1" aria-hidden="true" tabindex="-1"></a>bysubj <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="chapter-descriptive-stats.html#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="chapter-descriptive-stats.html#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb45-4"><a href="chapter-descriptive-stats.html#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">stdev =</span> <span class="fu">sd</span>(bdi)</span>
<span id="cb45-5"><a href="chapter-descriptive-stats.html#cb45-5" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   group stdev
##   &lt;fct&gt; &lt;dbl&gt;
## 1 ctl    2.83
## 2 mdd    6.61</code></pre>
</div>
</div>
<div id="indici-di-variabilità-relativi" class="section level3" number="4.8.5">
<h3><span class="header-section-number">4.8.5</span> Indici di variabilità relativi</h3>
<p>A volte può essere interessante effettuare un confronto fra due misure
di variabilità di grandezze incommensurabili, ovvero di caratteri
rilevati mediante differenti unità di misura. In questi casi, le misure
di variabilità precedentemente descritte si rivelano inadeguate in
quanto dipendono dall’unità di misura adottata. Diventa dunque
necessario ricorrere a particolari numeri adimensionali detti indici
relativi di variabilità. Il più importante di tali indici è il
coefficiente di variazione, ovvero il numero puro
<span class="math display">\[C_v = \frac{\sigma}{\bar{x}}\]</span> ottenuto dal rapporto tra la deviazione
standard e la media dei dati. Un altro indice relativo di variabilità è
la differenza interquartile rapportata al primo quartile oppure al terzo
quartile oppure alla mediana, cioè:
<span class="math display">\[\frac{x_{0.75} - x_{0.25}}{x_{0.25}}, \qquad \frac{x_{0.75} - x_{0.25}}{x_{0.75}}, \qquad \frac{x_{0.75} - x_{0.25}}{x_{0.50}}.\notag\]</span></p>
</div>
</div>
<div id="le-relazioni-tra-variabili" class="section level2" number="4.9">
<h2><span class="header-section-number">4.9</span> Le relazioni tra variabili</h2>
<p><span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span> hanno misurato il livello di depressione dei
soggetti del loro esperimento utilizzando due scale psicometriche: il
Beck Depression Inventory II (BDI-II) e la Center for Epidemiologic
Studies Depression Scale (CES-D). Il BDI-II è uno strumento self-report
che valutare la presenza e l’intensità di sintomi depressivi in pazienti
adulti e adolescenti di almeno 13 anni di età con diagnosi psichiatrica
mentre la CES-D è una scala self-report progettata per misurare i
sintomi depressivi che sono stati vissuti nella settimana precedente
nella popolazione generale, specialmente quella degli
adolescenti/giovani adulti. Una domanda ovvia che ci può venire in
mente è: quanto sono simili le misure ottenute mediante queste due
scale?</p>
<p>È chiaro che i numeri prodotti dalle scale BDI-II e CES-D non possono
essere identici, e questo per due motivi: (1) la presenza degli errori
di misurazione e (2) l’unità di misura delle due variabili. L’errore di
misurazione corrompe sempre, almeno in parte, qualunque operazione di
misurazione. E questo è vero specialmente in psicologia dove
l’<em>attendibilità</em> degli strumenti di misurazione è minore che in altre
discipline (quali la fisica, ad esempio). Il secondo motivo per cui i
valori delle scale BDI-II e CES-D non possono essere uguali è che
l’unità di misura delle due scale è arbitraria. Infatti, qual è l’unità
di misura della depressione? Chi può dirlo! Ma, al di là delle
differenze derivanti dall’errore di misurazione e dalla differente unità
di misura, ci aspettiamo che, se le due scale misurano entrambe lo
stesso costrutto, allora i valori prodotti dalle due scale dovranno
essere tra loro <em>linearmente associati</em>. Per capire cosa si intende con
“associazione lineare” iniziamo a guardare i dati. Per fare questo
utilizziamo una rappresentazione grafica che va sotto il nome di
diagramma a dispersione.</p>
<div id="diagramma-a-dispersione" class="section level3" number="4.9.1">
<h3><span class="header-section-number">4.9.1</span> Diagramma a dispersione</h3>
<p>Il diagramma di dispersione è la rappresentazione grafica delle coppie
di punti individuati dalle variabili BDI-II e CES-D, e si ottiene
ponendo, ad esempio, i valori BDI-II sull’asse delle ascisse e quelli
del CES-D sull’asse delle ordinate. In tale grafico, fornito dalla
figura <a href="chapter-descriptive-stats.html#fig:zetsche-scatter">4.7</a>, cascun punto corrisponde ad un
individuo del quale, nel caso presente, conosciamo il livello di
depressione misurato dalle due scale psicometriche.
<!-- A tale grafico sono -->
<!-- state aggiunte le funzioni *marginali* (ovvero, che si riferiscono a -->
<!-- ciascuna variabile considerata singolarmente) di densità empirica che -->
<!-- abbiamo già incontrato in precedenza. --></p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="chapter-descriptive-stats.html#cb48-1" aria-hidden="true" tabindex="-1"></a>bysubj <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb48-2"><a href="chapter-descriptive-stats.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(esm_id, group) <span class="sc">%&gt;%</span> </span>
<span id="cb48-3"><a href="chapter-descriptive-stats.html#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb48-4"><a href="chapter-descriptive-stats.html#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">bdi =</span> <span class="fu">mean</span>(bdi),</span>
<span id="cb48-5"><a href="chapter-descriptive-stats.html#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">cesd =</span> <span class="fu">mean</span>(cesd_sum)</span>
<span id="cb48-6"><a href="chapter-descriptive-stats.html#cb48-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb48-7"><a href="chapter-descriptive-stats.html#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb48-8"><a href="chapter-descriptive-stats.html#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;esm_id&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="chapter-descriptive-stats.html#cb50-1" aria-hidden="true" tabindex="-1"></a>m_cesd <span class="ot">&lt;-</span> <span class="fu">mean</span>(bysubj<span class="sc">$</span>cesd)</span>
<span id="cb50-2"><a href="chapter-descriptive-stats.html#cb50-2" aria-hidden="true" tabindex="-1"></a>m_bdi <span class="ot">&lt;-</span> <span class="fu">mean</span>(bysubj<span class="sc">$</span>bdi)</span>
<span id="cb50-3"><a href="chapter-descriptive-stats.html#cb50-3" aria-hidden="true" tabindex="-1"></a>FONT_SIZE <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb50-4"><a href="chapter-descriptive-stats.html#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="chapter-descriptive-stats.html#cb50-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> bysubj <span class="sc">%&gt;%</span></span>
<span id="cb50-6"><a href="chapter-descriptive-stats.html#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb50-7"><a href="chapter-descriptive-stats.html#cb50-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x=</span>bdi, <span class="at">y=</span>cesd, <span class="at">color=</span>group)) <span class="sc">+</span></span>
<span id="cb50-8"><a href="chapter-descriptive-stats.html#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb50-9"><a href="chapter-descriptive-stats.html#cb50-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span> m_cesd, <span class="at">linetype=</span><span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>) <span class="sc">+</span></span>
<span id="cb50-10"><a href="chapter-descriptive-stats.html#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> m_bdi, <span class="at">linetype=</span><span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>) <span class="sc">+</span></span>
<span id="cb50-11"><a href="chapter-descriptive-stats.html#cb50-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">x=</span><span class="sc">-</span><span class="dv">1</span>, <span class="at">y=</span><span class="dv">16</span>, <span class="at">label=</span><span class="st">&quot;I&quot;</span>, <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">size=</span>FONT_SIZE) <span class="sc">+</span></span>
<span id="cb50-12"><a href="chapter-descriptive-stats.html#cb50-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">x=</span><span class="dv">0</span>, <span class="at">y=</span><span class="dv">46</span>, <span class="at">label=</span><span class="st">&quot;IV&quot;</span>, <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">size=</span>FONT_SIZE) <span class="sc">+</span></span>
<span id="cb50-13"><a href="chapter-descriptive-stats.html#cb50-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">x=</span><span class="dv">18</span>, <span class="at">y=</span><span class="dv">46</span>, <span class="at">label=</span><span class="st">&quot;III&quot;</span>, <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">size=</span>FONT_SIZE) <span class="sc">+</span></span>
<span id="cb50-14"><a href="chapter-descriptive-stats.html#cb50-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">x=</span><span class="dv">18</span>, <span class="at">y=</span><span class="dv">16</span>, <span class="at">label=</span><span class="st">&quot;II&quot;</span>, <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">size=</span>FONT_SIZE) <span class="sc">+</span></span>
<span id="cb50-15"><a href="chapter-descriptive-stats.html#cb50-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb50-16"><a href="chapter-descriptive-stats.html#cb50-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;BDI-II&quot;</span>,</span>
<span id="cb50-17"><a href="chapter-descriptive-stats.html#cb50-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;CESD&quot;</span></span>
<span id="cb50-18"><a href="chapter-descriptive-stats.html#cb50-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb50-19"><a href="chapter-descriptive-stats.html#cb50-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_apa</span>() <span class="sc">+</span></span>
<span id="cb50-20"><a href="chapter-descriptive-stats.html#cb50-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">&quot;none&quot;</span>) </span>
<span id="cb50-21"><a href="chapter-descriptive-stats.html#cb50-21" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div>
<div class="figure"><span id="fig:zetsche-scatter"></span>
<img src="Psicometria_files/figure-html/zetsche-scatter-1.png" alt="Associazione tra le variabili BDI-II e CES-D nello studio di @zetsche_future_2019. In rosso sono rappresentate le osservazioni del gruppo di controllo; in blu quelle dei pazienti." width="95%" />
<p class="caption">
Figura 4.7: Associazione tra le variabili BDI-II e CES-D nello studio di <span class="citation"><a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al.</a> (<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">2019</a>)</span>. In rosso sono rappresentate le osservazioni del gruppo di controllo; in blu quelle dei pazienti.
</p>
</div>
<p>Dalla figura <a href="chapter-descriptive-stats.html#fig:zetsche-scatter">4.7</a> possiamo vedere che i dati mostrano
una certa tendenza a disporsi attorno ad una retta – nel gergo
statistico, questo fatto viene espresso dicendo che i punteggi CES-D
tendono ad essere linearmente associati ai punteggi BDI-II. È ovvio,
tuttavia, che tale relazione lineare è lungi dall’essere perfetta – se
fosse perfetta, tutti i punti del diagramma a dispersione si
disporrebbero esattamente lungo una retta.</p>
<p>Il problema che ci poniamo è quello di trovare un indice numerico che
descriva di quanto la nube di punti si discosta da una perfetta
relazione lineare tra le due variabili. Per risolvere tale problema
dobbiamo specificare un indice statistico che descriva la direzione e la
forza della relazione lineare tra le due variabili. Ci sono vari indici
statistici che possiamo utilizzare a questo scopo.</p>
</div>
<div id="covarianza" class="section level3" number="4.9.2">
<h3><span class="header-section-number">4.9.2</span> Covarianza</h3>
<p>Iniziamo a considerare il più importante di tali indici, chiamato
<em>covarianza</em>. In realtà la definizione di questo indice non ci
sorprenderà più di tanto in quanto, in una forma solo apparentemente
diversa, l’abbiamo già incontrato in precedenza. Ci ricordiamo infatti
che la varianza di una generica variabile <span class="math inline">\(X\)</span> è definita come la media
degli scarti quadratici di ciascuna osservazione dalla media:
<span class="math display" id="eq:variance2">\[\begin{equation}
S_{XX} = \frac{1}{n} \sum_{i=1}^n(X_i - \bar{X}) (X_i - \bar{X}).
\tag{4.5}
\end{equation}\]</span>
Infatti, la varianza viene talvolta descritta come la “covarianza di una
variabile con sé stessa.”</p>
<p>Adesso facciamo un passo ulteriore. Invece di valutare la dispersione di
una sola variabile, chiediamoci come due variabili <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> “variano
insieme” (co-variano). È facile capire come una risposta a tale domanda
possa essere fornita da una semplice trasformazione della formula
precedente che diventa:
<span class="math display" id="eq:covariance">\[\begin{equation}
S_{XY} = \frac{1}{n} \sum_{i=1}^n(X_i - \bar{X}) (Y_i - \bar{Y}).
\tag{4.6}
\end{equation}\]</span>
L’eq. <a href="chapter-descriptive-stats.html#eq:covariance">(4.6)</a> ci fornisce dunque la definizione della covarianza.</p>
<p>Per capire il significato dell’eq. <a href="chapter-descriptive-stats.html#eq:covariance">(4.6)</a>, supponiamo di dividere il grafico della figura <a href="chapter-descriptive-stats.html#fig:zetsche-scatter">4.7</a> in quattro quadranti definiti da una retta verticale passante per la media dei valori BDI-II e da una
retta orizzontale passante per la media dei valori CES-D. Numeriamo i
quadranti partendo da quello in basso a sinistra e muovendoci in senso
antiorario.</p>
<p>Se prevalgono punti nel I e III quadrante, allora la nuvola di punti
avrà un andamento crescente (per cui a valori bassi di <span class="math inline">\(X\)</span> tendono ad
associarsi valori bassi di <span class="math inline">\(Y\)</span> e a valori elevati di <span class="math inline">\(X\)</span> tendono ad
associarsi valori elevati di <span class="math inline">\(Y\)</span>) e la covarianza segno positivo. Mentre
se prevalgono punti nel II e IV quadrante la nuvola di punti avrà un
andamento decrescente (per cui a valori bassi di <span class="math inline">\(X\)</span> tendono ad
associarsi valori elevati di <span class="math inline">\(Y\)</span> e a valori elevati di <span class="math inline">\(X\)</span> tendono ad
associarsi valori bassi di <span class="math inline">\(Y\)</span>) e la covarianza segno negativo. Dunque,
il segno della covarianza ci informa sulla direzione della relazione
lineare tra due variabili: l’associazione lineare si dice positiva se la
covarianza è positiva, negativa se la covarianza è negativa.</p>
<p>Il segno della covarianza ci informa sulla direzione della relazione, ma
invece il valore assoluto della covarianza ci dice ben poco. Esso,
infatti, dipende dall’unità di misura delle variabili. Nel caso presente
questo concetto è difficile da comprendere, dato che le due variabili in
esame non hanno un’unità di misura (ovvero, hanno un’unità di misura
arbitraria e priva di significato). Ma quest’idea diventa chiara se
pensiamo alla relazione lineare tra l’altezza e il peso delle persone,
ad esempio. La covarianza tra queste due quantità è certamente positiva,
ma il valore assoluto della covarianza diventa più grande se l’altezza
viene misurata in millimetri e il peso in grammi, e diventa più piccolo
l’altezza viene misurata in metri e il peso in chilogrammi. Dunque, il
valore della covarianza cambia al mutare dell’unità di misura delle
variabili anche se l’associazione tra le variabili resta costante.</p>
</div>
<div id="correlazione" class="section level3" number="4.9.3">
<h3><span class="header-section-number">4.9.3</span> Correlazione</h3>
<p>Dato che il valore assoluto della covarianza è di difficile
interpretazione – in pratica, non viene mai interpretato – è
necessario trasformare la covarianza in modo tale da renderla immune
alle trasformazioni dell’unità di misura delle variabili. Questa
operazione si dice <em>standardizzazione</em> e corrisponde alla divisione
della covarianza per le deviazioni standard (<span class="math inline">\(s_X\)</span>, <span class="math inline">\(s_Y\)</span>) delle due
variabili:</p>
<p><span class="math display" id="eq:correlation">\[\begin{equation}
r_{XY} = \frac{S_{XY}}{s_X s_Y}.
\tag{4.7}
\end{equation}\]</span>
La quantià che si ottiene in questo modo viene chiamata <em>correlazione</em> di Bravais-Pearson (dal nome degli autori che, indipendentemente l’uno dall’altro, la hanno introdotta).</p>
<p>Il coefficiente di correlazione ha le seguenti proprietà:</p>
<ul>
<li>ha lo stesso segno della covarianza, dato che si ottiene dividendo
la covarianza per due numeri positivi;</li>
<li>è un numero puro, cioè non dipende dall’unità di misura delle
variabili;</li>
<li>assume valori compresi tra -1 e +1.</li>
</ul>
<p>Ad esso possiamo assegnare la seguente interpretazione:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(r_{XY} = -1\)</span> <span class="math inline">\(\rightarrow\)</span> perfetta relazione negativa: tutti i
punti si trovano esattamente su una retta con pendenza negativa (dal
quadrante in alto a sinistra al quadrante in basso a destra);</li>
<li><span class="math inline">\(r_{XY} = +1\)</span> <span class="math inline">\(\rightarrow\)</span> perfetta relazione positiva: tutti i
punti si trovano esattamente su una retta con pendenza positiva (dal
quadrante in basso a sinistra al quadrante in alto a destra);</li>
<li><span class="math inline">\(-1 &lt; r_{XY} &lt; +1\)</span> <span class="math inline">\(\rightarrow\)</span> presenza di una relazione lineare
di intensità diversa;</li>
<li><span class="math inline">\(r_{XY} = 0\)</span> <span class="math inline">\(\rightarrow\)</span> assenza di relazione lineare tra <span class="math inline">\(X\)</span> e
<span class="math inline">\(Y\)</span>.</li>
</ol>
<p>Per i dati della figura <a href="chapter-descriptive-stats.html#fig:zetsche-scatter">4.7</a>, la covarianza è 207.426. Il segno positivo della covarianza ci dice che tra le due variabili c’è
un’associazione lineare positiva. Per capire qual è l’intensità della
relazione lineare tra le due variabili calcoliamo la correlazione.
Essendo le deviazioni standard del BDI-II e del CES-D rispettavamente
uguali a 15.37 e 14.93, la correlazione diventa uguale a
<span class="math inline">\(\frac{207.426}{15.38 \cdot 14.93} = 0.904.\)</span> Tale valore è prossimo a
1.0, il che vuol dire che i punti del diagramma a dispersione non si
discostano troppo da una retta con una pendenza positiva.</p>
</div>
</div>
<div id="correlazione-e-causazione" class="section level2" number="4.10">
<h2><span class="header-section-number">4.10</span> Correlazione e causazione</h2>
<p>Facendo riferimento nuovamente alla figura <a href="chapter-descriptive-stats.html#fig:zetsche-scatter">4.7</a>, possiamo dire che, in molte applicazioni (ma non nel caso presente!) l’asse <span class="math inline">\(x\)</span> rappresenta una
quantità nota come <em>variabile indipendente</em> e l’interesse si concentra
sulla sua influenza sulla <em>variabile dipendente</em> tracciata sull’asse
<span class="math inline">\(y\)</span>. Ciò presuppone però che sia nota la direzione in cui l’influenza
causale potrebbe risiedere. È importante tenere bene a mente che la
correlazione è soltanto un indice descrittivo della relazione lineare
tra due variabili e in nessun caso può essere usata per inferire
alcunché sulle relazioni <strong>causali</strong> che legano le variabili. È ben nota
l’espressione: “correlazione non significa causazione.”</p>
<p>Di opinione diversa era invece Karl Pearson (1911), il quale ha
affermato:</p>
<blockquote>
<p>Quanto spesso, quando è stato osservato un nuovo fenomeno,
sentiamo che viene posta la domanda: ‘qual è la sua causa?’ Questa è
una domanda a cui potrebbe essere assolutamente impossibile rispondere.
Invece, può essere più facile rispondere alla domanda: ‘in che misura
altri fenomeni sono associati con esso?’ Dalla risposta a questa
seconda domanda possono risultare molte preziose conoscenze.</p>
</blockquote>
<p>Che alla seconda domanda posta da Pearson sia facile rispondere è indubbio. Che
la nostra comprensione di un fenomeno possa aumentare sulla base delle
informazioni fornite dalle correlazioni, invece, è molto dubbio e quasi
certamente falso.</p>
<div id="usi-della-correlazione" class="section level3" number="4.10.1">
<h3><span class="header-section-number">4.10.1</span> Usi della correlazione</h3>
<p>Anche se non può essere usata per studiare le relazioni causali, la
correlazione viene usata per molti altri scopi tra i quali, per esempio,
quello di misurare la <em>validità concorrente</em> di un test psiologico. Se
un test psicologico misura effettivamente ciò che ci si aspetta che
misuri (nel caso dell’esempio presente, la depressione), allora dovremo
aspettarci che fornisca una correlazione alta con risultati di altri
test che misurano lo stesso costrutto – come nel caso dei dati di
<span class="citation">(<a href="bibliografia.html#ref-zetsche_future_2019" role="doc-biblioref">Zetsche et al., 2019</a>)</span>. Un’altra proprietà desiderabile di un test
psicometrico è la <em>validità divergente</em>: i risultati di test
psicometrici che misurano costrutti diversi dovrebbero essere poco
associati tra loro. In altre parole, in questo secondo caso dovremmo
aspettarci che la correlazione sia bassa.</p>
</div>
<div id="correlazione-di-spearman" class="section level3" number="4.10.2">
<h3><span class="header-section-number">4.10.2</span> Correlazione di Spearman</h3>
<p>Una misura alternativa della relazione lineare tra due variabili è
fornita dal coefficiente di correlazione di Spearman e dipende soltanto
dalla relazione d’ordine dei dati, non dagli specifici valori dei dati.
Tale misura di associazione è appropriata quando, del fenomeno in esame,
gli psicologi sono stati in grado di misurare soltanto le relazioni
d’ordine tra le diverse modalità della risposta dei soggetti, non
l’intensità della risposta. Le variabili psicologiche che hanno questa
proprietà si dicono <em>ordinali</em>. Nel caso di variabili ordinali, non è
possibile sintetizzare i dati mediante le statistiche descrittive che
abbiamo introdotto in questo capitolo, quali ad esempio la media e la
varianza, ma è invece solo possibile riassumere i dati mediante una
distribuzione di frequenze per le varie modalità della risposta.</p>
</div>
<div id="correlazione-nulla" class="section level3" number="4.10.3">
<h3><span class="header-section-number">4.10.3</span> Correlazione nulla</h3>
<p>Un ultimo aspetto da mettere in evidenza a proposito della correlazione
riguarda il fatto che la correlazione descrive la direzione e
l’intensità della relazione lineare tra due variabili. Relazioni non
lineari tra le variabili, anche sono molto forti, non vengono catturate
dalla correlazione. È importante rendersi conto che una correlazione
pari a zero non significa che non c’è relazione tra le due variabili, ma
solo che tra esse non c’è una relazione <em>lineare</em>. Un esempio di questo
fatto è fornito dalla figura <a href="chapter-descriptive-stats.html#fig:zerocorr">4.8</a>.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="chapter-descriptive-stats.html#cb51-1" aria-hidden="true" tabindex="-1"></a>slant <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datasaurus_dozen_wide, <span class="fu">aes</span>(<span class="at">x=</span>slant_down_x,<span class="at">y=</span>slant_down_y),   <span class="at">colour=</span>dataset) </span>
<span id="cb51-2"><a href="chapter-descriptive-stats.html#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="co"># loads slant-pattern dataset of datasauRus package into data frame slant</span></span>
<span id="cb51-3"><a href="chapter-descriptive-stats.html#cb51-3" aria-hidden="true" tabindex="-1"></a>slant <span class="ot">&lt;-</span> slant <span class="sc">+</span> </span>
<span id="cb51-4"><a href="chapter-descriptive-stats.html#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="co"># as a scatter type geom</span></span>
<span id="cb51-5"><a href="chapter-descriptive-stats.html#cb51-5" aria-hidden="true" tabindex="-1"></a>slant <span class="ot">&lt;-</span> slant <span class="sc">+</span> </span>
<span id="cb51-6"><a href="chapter-descriptive-stats.html#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="co"># eliminates unwanted axis labels</span></span>
<span id="cb51-7"><a href="chapter-descriptive-stats.html#cb51-7" aria-hidden="true" tabindex="-1"></a>slant <span class="ot">&lt;-</span> slant <span class="sc">+</span> </span>
<span id="cb51-8"><a href="chapter-descriptive-stats.html#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>, </span>
<span id="cb51-9"><a href="chapter-descriptive-stats.html#cb51-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.border =</span> <span class="fu">element_rect</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="cn">NA</span>, <span class="at">size =</span> <span class="dv">1</span>),</span>
<span id="cb51-10"><a href="chapter-descriptive-stats.html#cb51-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">0</span>,<span class="dv">2</span>), <span class="at">aspect.ratio =</span> <span class="dv">1</span>) </span>
<span id="cb51-11"><a href="chapter-descriptive-stats.html#cb51-11" aria-hidden="true" tabindex="-1"></a><span class="co"># removes legend, adds a border, adds margin space below, and specifies </span></span>
<span id="cb51-12"><a href="chapter-descriptive-stats.html#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="co"># required aspect ratio</span></span>
<span id="cb51-13"><a href="chapter-descriptive-stats.html#cb51-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-14"><a href="chapter-descriptive-stats.html#cb51-14" aria-hidden="true" tabindex="-1"></a>dino <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datasaurus_dozen_wide, <span class="fu">aes</span>(<span class="at">x=</span>dino_x,<span class="at">y=</span>dino_y), <span class="at">colour=</span>dataset) <span class="sc">+</span></span>
<span id="cb51-15"><a href="chapter-descriptive-stats.html#cb51-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() </span>
<span id="cb51-16"><a href="chapter-descriptive-stats.html#cb51-16" aria-hidden="true" tabindex="-1"></a><span class="co"># loads dino-figure dataset of datasauRus package into data </span></span>
<span id="cb51-17"><a href="chapter-descriptive-stats.html#cb51-17" aria-hidden="true" tabindex="-1"></a><span class="co">#frame dino as a scatter type geom</span></span>
<span id="cb51-18"><a href="chapter-descriptive-stats.html#cb51-18" aria-hidden="true" tabindex="-1"></a>dino <span class="ot">&lt;-</span> dino <span class="sc">+</span><span class="fu">theme_void</span>() <span class="co"># eliminates unwanted axis labels</span></span>
<span id="cb51-19"><a href="chapter-descriptive-stats.html#cb51-19" aria-hidden="true" tabindex="-1"></a>dino <span class="ot">&lt;-</span> dino <span class="sc">+</span> </span>
<span id="cb51-20"><a href="chapter-descriptive-stats.html#cb51-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>, </span>
<span id="cb51-21"><a href="chapter-descriptive-stats.html#cb51-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.border =</span>  <span class="fu">element_rect</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="cn">NA</span>, <span class="at">size =</span> <span class="dv">1</span>),</span>
<span id="cb51-22"><a href="chapter-descriptive-stats.html#cb51-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">0</span>,<span class="dv">2</span>), <span class="at">aspect.ratio =</span> <span class="dv">1</span>) </span>
<span id="cb51-23"><a href="chapter-descriptive-stats.html#cb51-23" aria-hidden="true" tabindex="-1"></a><span class="co"># removes legend, adds a border, adds margin space below, specifies </span></span>
<span id="cb51-24"><a href="chapter-descriptive-stats.html#cb51-24" aria-hidden="true" tabindex="-1"></a><span class="co"># required aspect ratio</span></span>
<span id="cb51-25"><a href="chapter-descriptive-stats.html#cb51-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-26"><a href="chapter-descriptive-stats.html#cb51-26" aria-hidden="true" tabindex="-1"></a>slant <span class="sc">+</span> dino</span></code></pre></div>
<div class="figure"><span id="fig:zerocorr"></span>
<img src="Psicometria_files/figure-html/zerocorr-1.png" alt="Due insiemi di dati (fittizi) per i quali i coefficienti di correlazione di Pearson sono entrambi 0. Ma questo non significa che non vi sia alcuna relazione tra le variabili." width="80%" />
<p class="caption">
Figura 4.8: Due insiemi di dati (fittizi) per i quali i coefficienti di correlazione di Pearson sono entrambi 0. Ma questo non significa che non vi sia alcuna relazione tra le variabili.
</p>
</div>
</div>
</div>
<div id="conclusioni" class="section level2 unnumbered">
<h2>Conclusioni</h2>
<p>La prima fase dell’analisi dei dati è sicuramente quella che ci porta a
riassumere i dati mediante gli strumenti della statistica descrittiva.
Ci sono diverse domande che vengono affrontate in questa fase: qual è la
distribuzione delle variabili di interesse? Quali relazioni a coppie si
possono osservare nel campione? Ci sono delle osservazioni ‘anomale,’
ovvero estremamente discrepanti rispetto alle altre, sia quando si
esaminano le statistiche descrittive univariate (ovvero, quelle che
riguardano le caratteristiche di una variabile presa singolarmente), sia
quando vengono esaminate le statistiche bivariate (ovvero, le
statistiche che descrivono l’associazione tra le variabili)? È
importante avere ben chiare le idee su questi punti prima di procedere
con qualsiasi procedura statistica di tipo inferenziale. Per rispondere
alle domande che abbiamo elencato sopra, ed ad altre simili, è molto
utile procedere con delle rappresentazioni grafiche dei dati. Dovrebbe
essere chiaro che, quando disponiamo di grandi moli di dati (come è
sempre il caso in psicologia), per fare questo è necessario usare un
software statistico.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chapter-misurazione.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter-prob-discreta.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ccaudek/bookdown_psicometria/edit/master/04_stat_descrittive.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/ccaudek/bookdown_psicometria/blob/master/04_stat_descrittive.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
